package web

// Authentication, kept in one file so that it can be reviewed on its own.
//
// Credentials:
//
//   - The run token: 256 random bits, generated by newAuthority, never accepted from outside the
//     process and printed only by Server.URL. It is compared in constant time (both sides hashed
//     first, so lengths do not leak), and it is accepted as "Authorization: Bearer" on any route and
//     as "?token=" on the page URL "/" only.
//   - The session cookie: 256 random bits unrelated to the token. The server keeps the sessions
//     (keyed by a hash of the id, so the id itself is not held), each with an absolute expiry, and
//     can end one (logout) or all of them (rotate). The cookie is HttpOnly and SameSite=Strict, and
//     Secure whenever the request came over TLS.
//
// Failed attempts to present the token are counted for the whole server (every client of a
// loopback socket looks alike). When too many fail inside the window, further attempts are refused
// with 429 without being evaluated, so the token cannot be guessed at line rate. A session cookie
// is a different credential: it is looked up, never throttled, and its failures are not counted,
// because a stale cookie after a restart is routine.
//
// Confirmations (Server.IssueConfirm) are second-factor ids for privilege-raising routes: single
// use, short-lived, bound to the credential that asked and to one scope.

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	// CookieName is the name of the session cookie.
	CookieName = "sleipnir_web"

	// ConfirmHeader carries a confirmation id on routes that need one.
	ConfirmHeader = "X-Confirm"

	// maxCredentialLen bounds any presented credential before it is hashed.
	maxCredentialLen = 256
	// maxSessions bounds the sessions kept; creating one beyond it ends the oldest.
	maxSessions = 32
	// maxConfirms and maxConfirmsPerPrincipal bound outstanding confirmation ids.
	maxConfirms             = 256
	maxConfirmsPerPrincipal = 16
	// maxScopeLen bounds a confirmation scope.
	maxScopeLen = 120
)

// Failures that make the next token attempt a 429 instead of a 401, by default: 10 failures in a
// minute.
const (
	defaultAuthFailures = 10
	defaultAuthWindow   = time.Minute
)

// credKind says what a request authenticated with.
type credKind int

const (
	credNone credKind = iota
	credCookie
	credBearer
)

// principal is an authenticated caller: a session or the bearer token.
type principal struct {
	id    string
	kind  credKind
	sum   [sha256.Size]byte // the session's key, for logout
	done  <-chan struct{}   // closed when the credential is revoked
	valid func() bool       // false once the credential expired or was revoked
}

// errBadCredential is a presented credential that is wrong.
var errBadCredential = errors.New("web: wrong credential")

// throttleError is a refusal to evaluate a token attempt.
type throttleError struct{ retryAfter time.Duration }

// Error describes the refusal.
func (e *throttleError) Error() string { return "web: too many failed attempts" }

// errConfirmInvalid is a confirmation id that is unknown, used, expired or for something else.
var errConfirmInvalid = errors.New("web: invalid confirmation")

// epoch is one generation of the run token; bearer principals belong to the one that issued
// them, and rotation ends it.
type epoch struct {
	n    uint64
	done chan struct{}
}

// session is a server-side login.
type session struct {
	created time.Time
	expires time.Time
	done    chan struct{}
}

// confirm is an outstanding confirmation id.
type confirm struct {
	principal string
	scope     string
	expires   time.Time
}

// failureWindow counts failures inside a sliding window.
type failureWindow struct {
	max    int
	window time.Duration
	times  []time.Time
}

// blocked reports whether the window is full at now, and when the oldest failure leaves it.
func (f *failureWindow) blocked(now time.Time) (bool, time.Duration) {
	keep := f.times[:0]
	for _, t := range f.times {
		if now.Sub(t) < f.window {
			keep = append(keep, t)
		}
	}
	f.times = keep
	if len(f.times) < f.max {
		return false, 0
	}
	return true, f.times[0].Add(f.window).Sub(now)
}

// record notes a failure at now, remembering no more than max of them.
func (f *failureWindow) record(now time.Time) {
	f.times = append(f.times, now)
	if len(f.times) > f.max {
		f.times = f.times[len(f.times)-f.max:]
	}
}

// authority holds the token, the sessions and the confirmations.
type authority struct {
	mu         sync.Mutex
	now        func() time.Time
	ttl        time.Duration
	confirmTTL time.Duration
	token      string
	tokenSum   [sha256.Size]byte
	epoch      *epoch
	sessions   map[[sha256.Size]byte]*session
	confirms   map[[sha256.Size]byte]*confirm
	fails      failureWindow
}

// randomString returns n random bytes as unpadded URL-safe base64.
func randomString(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// newAuthority creates an authority with a fresh random token. It fails only if the system has
// no randomness, in which case no server should start.
func newAuthority(now func() time.Time, ttl, confirmTTL time.Duration) (*authority, error) {
	a := &authority{
		now: now, ttl: ttl, confirmTTL: confirmTTL,
		sessions: map[[sha256.Size]byte]*session{},
		confirms: map[[sha256.Size]byte]*confirm{},
		fails:    failureWindow{max: defaultAuthFailures, window: defaultAuthWindow},
	}
	if err := a.newTokenLocked(); err != nil {
		return nil, err
	}
	return a, nil
}

// newTokenLocked replaces the token and starts a new epoch.
func (a *authority) newTokenLocked() error {
	t, err := randomString(32)
	if err != nil {
		return err
	}
	a.token = t
	a.tokenSum = sha256.Sum256([]byte(t))
	n := uint64(1)
	if a.epoch != nil {
		n = a.epoch.n + 1
	}
	a.epoch = &epoch{n: n, done: make(chan struct{})}
	return nil
}

// currentToken returns the token, for the URL and for log masking.
func (a *authority) currentToken() string {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.token
}

// tokenOKLocked compares a presented token with the real one in constant time.
func (a *authority) tokenOKLocked(given string) bool {
	if given == "" || len(given) > maxCredentialLen {
		return false
	}
	sum := sha256.Sum256([]byte(given))
	return subtle.ConstantTimeCompare(sum[:], a.tokenSum[:]) == 1
}

// checkAttemptLocked refuses the attempt when too many have failed lately.
func (a *authority) checkAttemptLocked() error {
	if blocked, wait := a.fails.blocked(a.now()); blocked {
		return &throttleError{retryAfter: wait}
	}
	return nil
}

// bearerPrincipalLocked is the principal of the current token.
func (a *authority) bearerPrincipalLocked() *principal {
	ep := a.epoch
	return &principal{
		id: "token#" + strconv.FormatUint(ep.n, 10), kind: credBearer, done: ep.done,
		valid: func() bool {
			a.mu.Lock()
			defer a.mu.Unlock()
			return a.epoch == ep
		},
	}
}

// bearer checks a token presented in the Authorization header.
func (a *authority) bearer(given string) (*principal, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	if err := a.checkAttemptLocked(); err != nil {
		return nil, err
	}
	if !a.tokenOKLocked(given) {
		a.fails.record(a.now())
		return nil, errBadCredential
	}
	return a.bearerPrincipalLocked(), nil
}

// exchange checks the token of a page URL and, if it is right, starts a session and returns the
// cookie value that names it.
func (a *authority) exchange(given string) (string, *principal, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	if err := a.checkAttemptLocked(); err != nil {
		return "", nil, err
	}
	if !a.tokenOKLocked(given) {
		a.fails.record(a.now())
		return "", nil, errBadCredential
	}
	return a.newSessionLocked()
}

// newSessionLocked starts a session, ending the oldest if there are too many, and returns the
// cookie value and the principal.
func (a *authority) newSessionLocked() (string, *principal, error) {
	id, err := randomString(32)
	if err != nil {
		return "", nil, err
	}
	now := a.now()
	for k, s := range a.sessions {
		if !now.Before(s.expires) {
			a.endSessionLocked(k)
		}
	}
	for len(a.sessions) >= maxSessions {
		var oldest [sha256.Size]byte
		var at time.Time
		first := true
		for k, s := range a.sessions {
			if first || s.created.Before(at) {
				oldest, at, first = k, s.created, false
			}
		}
		a.endSessionLocked(oldest)
	}
	sum := sha256.Sum256([]byte(id))
	a.sessions[sum] = &session{created: now, expires: now.Add(a.ttl), done: make(chan struct{})}
	return id, a.sessionPrincipalLocked(sum), nil
}

// sessionPrincipalLocked is the principal of the session with the given key.
func (a *authority) sessionPrincipalLocked(sum [sha256.Size]byte) *principal {
	s := a.sessions[sum]
	return &principal{
		id: "session#" + hex.EncodeToString(sum[:]), kind: credCookie, sum: sum, done: s.done,
		valid: func() bool {
			a.mu.Lock()
			defer a.mu.Unlock()
			cur := a.sessions[sum]
			return cur == s && a.now().Before(s.expires)
		},
	}
}

// endSessionLocked removes a session, closes the streams that depend on it and drops its
// confirmations.
func (a *authority) endSessionLocked(sum [sha256.Size]byte) {
	s := a.sessions[sum]
	if s == nil {
		return
	}
	delete(a.sessions, sum)
	close(s.done)
	id := "session#" + hex.EncodeToString(sum[:])
	for k, c := range a.confirms {
		if c.principal == id {
			delete(a.confirms, k)
		}
	}
}

// lookup returns the principal of a cookie value, or nil if it names no live session.
func (a *authority) lookup(value string) *principal {
	if value == "" || len(value) > maxCredentialLen {
		return nil
	}
	sum := sha256.Sum256([]byte(value))
	a.mu.Lock()
	defer a.mu.Unlock()
	s := a.sessions[sum]
	if s == nil {
		return nil
	}
	if !a.now().Before(s.expires) {
		a.endSessionLocked(sum)
		return nil
	}
	return a.sessionPrincipalLocked(sum)
}

// logout ends the session of a cookie principal.
func (a *authority) logout(p *principal) {
	if p == nil || p.kind != credCookie {
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	a.endSessionLocked(p.sum)
}

// rotate ends every session, every confirmation and the token itself, and starts a fresh session
// for the caller. Nobody learns the new token: the point is to cut off every other holder of the
// old one, and the caller keeps working through the new cookie.
func (a *authority) rotate() (string, *principal, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	close(a.epoch.done)
	for k := range a.sessions {
		a.endSessionLocked(k)
	}
	a.confirms = map[[sha256.Size]byte]*confirm{}
	a.fails.times = nil
	if err := a.newTokenLocked(); err != nil {
		return "", nil, err
	}
	return a.newSessionLocked()
}

// sweepConfirmsLocked drops expired confirmations.
func (a *authority) sweepConfirmsLocked() {
	now := a.now()
	for k, c := range a.confirms {
		if !now.Before(c.expires) {
			delete(a.confirms, k)
		}
	}
}

// issueConfirm creates a single-use id for scope, bound to p. It returns "" when p already has
// too many outstanding or the server has.
func (a *authority) issueConfirm(p *principal, scope string) string {
	a.mu.Lock()
	defer a.mu.Unlock()
	a.sweepConfirmsLocked()
	if len(a.confirms) >= maxConfirms {
		return ""
	}
	n := 0
	for _, c := range a.confirms {
		if c.principal == p.id {
			n++
		}
	}
	if n >= maxConfirmsPerPrincipal {
		return ""
	}
	id, err := randomString(24)
	if err != nil {
		return ""
	}
	a.confirms[sha256.Sum256([]byte(id))] = &confirm{principal: p.id, scope: scope, expires: a.now().Add(a.confirmTTL)}
	return id
}

// consumeConfirm checks and uses up a confirmation id. An id is spent by the first attempt to use
// it, whether or not the attempt was right, so that a wrong scope cannot be probed repeatedly.
func (a *authority) consumeConfirm(p *principal, scope, id string) error {
	if id == "" || len(id) > maxCredentialLen {
		return errConfirmInvalid
	}
	key := sha256.Sum256([]byte(id))
	a.mu.Lock()
	defer a.mu.Unlock()
	c := a.confirms[key]
	if c == nil {
		return errConfirmInvalid
	}
	delete(a.confirms, key)
	if p == nil || c.principal != p.id || c.scope != scope || !a.now().Before(c.expires) {
		return errConfirmInvalid
	}
	return nil
}

// validScope reports whether s can be a confirmation scope: printable ASCII, bounded.
func validScope(s string) bool {
	if s == "" || len(s) > maxScopeLen {
		return false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < 0x20 || s[i] > 0x7e {
			return false
		}
	}
	return true
}

// ---- the envelope's use of the authority ----------------------------------------------------

// authenticate establishes who the request is from, or answers it. It returns false when the
// response has been written. The page URL "/" with a token parameter is the one place a token
// from the URL is accepted: it becomes a cookie and a redirect that removes it.
func (s *Server) authenticate(w http.ResponseWriter, r *http.Request, info *reqInfo) bool {
	safe := r.Method == http.MethodGet || r.Method == http.MethodHead
	if safe && r.URL.Path == "/healthz" {
		return true
	}
	if safe && r.URL.Path == "/" {
		if t := r.URL.Query().Get("token"); t != "" {
			cookie, _, err := s.auth.exchange(t)
			switch {
			case err == nil:
				s.startSession(w, r, cookie)
				return false
			case isThrottle(err):
				s.throttled(w, err)
				return false
			}
			// a wrong token in the URL (a bookmark from an earlier run) does not hide a good cookie
		}
	}
	if h := r.Header.Get("Authorization"); h != "" {
		if scheme, value, ok := strings.Cut(h, " "); ok && strings.EqualFold(scheme, "bearer") {
			p, err := s.auth.bearer(strings.TrimSpace(value))
			switch {
			case err == nil:
				info.p = p
				return true
			case isThrottle(err):
				s.throttled(w, err)
				return false
			}
			s.unauthenticated(w, r)
			return false
		}
	}
	for _, c := range r.CookiesNamed(CookieName) {
		if p := s.auth.lookup(c.Value); p != nil {
			info.p = p
			return true
		}
	}
	s.unauthenticated(w, r)
	return false
}

// isThrottle reports whether err is a refusal to evaluate.
func isThrottle(err error) bool {
	var t *throttleError
	return errors.As(err, &t)
}

// throttled answers an attempt that was not evaluated.
func (s *Server) throttled(w http.ResponseWriter, err error) {
	var t *throttleError
	secs := 1
	if errors.As(err, &t) {
		secs = int(t.retryAfter/time.Second) + 1
	}
	w.Header().Set("Retry-After", strconv.Itoa(secs))
	Error(w, http.StatusTooManyRequests, "rate_limited", "too many failed attempts to present the token; wait and try again")
}

// signInPage is what a browser sees when it opens the server without a session. It holds no
// script, no style and no data.
const signInPage = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>Sleipnir: sign-in required</title>
</head>
<body>
<h1>Sign-in required</h1>
<p>Open the link printed on the first line of the terminal that runs <code>sleipnir web</code>.
It carries a token that is valid for that run only, and this page keeps a session in a cookie afterwards.</p>
</body>
</html>
`

// unauthenticated answers a request that presented no valid credential: a small page for a
// browser that navigated here, JSON for everything else.
func (s *Server) unauthenticated(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("WWW-Authenticate", `Bearer realm="sleipnir-web"`)
	if r.Method == http.MethodGet && r.Header.Get(RequestHeader) == "" && !strings.HasPrefix(r.URL.Path, "/api/") &&
		strings.Contains(r.Header.Get("Accept"), "text/html") {
		h := w.Header()
		h.Set("Content-Type", "text/html; charset=utf-8")
		h.Set("Cache-Control", "no-store")
		w.WriteHeader(http.StatusUnauthorized)
		_, _ = w.Write([]byte(signInPage))
		return
	}
	Error(w, http.StatusUnauthorized, "unauthenticated",
		"authentication is required: open the URL printed by `sleipnir web`, or send the run token as Authorization: Bearer")
}

// setSessionCookie sends the cookie that names a session.
func (s *Server) setSessionCookie(w http.ResponseWriter, r *http.Request, value string) {
	http.SetCookie(w, &http.Cookie{
		Name: CookieName, Value: value, Path: "/", HttpOnly: true, SameSite: http.SameSiteStrictMode,
		Secure: r.TLS != nil, MaxAge: int(s.cfg.SessionTTL / time.Second), Expires: s.auth.now().Add(s.cfg.SessionTTL),
	})
}

// startSession answers a good token in the page URL: the cookie, and a redirect to "/" with the
// token removed. The target is always the root path of this server, with the other query
// parameters re-encoded, so it cannot name another origin.
func (s *Server) startSession(w http.ResponseWriter, r *http.Request, cookie string) {
	s.setSessionCookie(w, r, cookie)
	q := r.URL.Query()
	q.Del("token")
	loc := "/"
	if enc := q.Encode(); enc != "" && len(enc) <= 2048 {
		loc += "?" + enc
	}
	w.Header().Set("Cache-Control", "no-store")
	http.Redirect(w, r, loc, http.StatusSeeOther)
}

// clearSessionCookie tells the browser to forget the cookie.
func (s *Server) clearSessionCookie(w http.ResponseWriter, r *http.Request) {
	http.SetCookie(w, &http.Cookie{
		Name: CookieName, Value: "", Path: "/", HttpOnly: true, SameSite: http.SameSiteStrictMode,
		Secure: r.TLS != nil, MaxAge: -1,
	})
}

// handleLogout ends the caller's session. A bearer caller has no session to end.
func (s *Server) handleLogout(w http.ResponseWriter, r *http.Request) {
	info := infoFrom(r.Context())
	s.auth.logout(info.p)
	s.clearSessionCookie(w, r)
	_ = WriteJSON(w, http.StatusOK, map[string]any{"ok": true})
}

// handleRotate ends every session and the token, and gives the caller a fresh session. It is for a
// browser: a bearer caller would be locked out by it, so it is refused.
func (s *Server) handleRotate(w http.ResponseWriter, r *http.Request) {
	info := infoFrom(r.Context())
	if info.p == nil || info.p.kind != credCookie {
		Error(w, http.StatusForbidden, "forbidden", "only a browser session can rotate the token")
		return
	}
	cookie, _, err := s.auth.rotate()
	if err != nil {
		Logf(r, "rotating the token: %v", err)
		Error(w, http.StatusInternalServerError, "internal", "could not rotate the token")
		return
	}
	s.setSessionCookie(w, r, cookie)
	Logf(r, "the run token was rotated; every other session ended")
	_ = WriteJSON(w, http.StatusOK, map[string]any{"ok": true})
}

// handleConfirm issues a confirmation id for the scope in the body.
func (s *Server) handleConfirm(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Scope string `json:"scope"`
	}
	if !DecodeJSON(w, r, &body) {
		return
	}
	if !validScope(body.Scope) {
		Error(w, http.StatusBadRequest, "bad_request", "scope must be 1 to 120 printable ASCII characters")
		return
	}
	id := s.IssueConfirm(r, body.Scope)
	if id == "" {
		Error(w, http.StatusTooManyRequests, "rate_limited", "too many confirmations are outstanding; use or wait for them")
		return
	}
	_ = WriteJSON(w, http.StatusOK, map[string]any{
		"id": id, "scope": body.Scope, "expires_in": int(s.cfg.ConfirmTTL / time.Second),
	})
}

// IssueConfirm returns a single-use confirmation id for scope, bound to the credential that made
// the request r: it can be spent only by a request authenticated by that same session (or, for a
// bearer caller, the same token), only on a route whose confirmation scope is scope, and only
// within Config.ConfirmTTL. The client sends it as the X-Confirm header. It returns "" when r is
// not authenticated, scope is not 1 to 120 printable ASCII characters, or too many ids are
// outstanding.
func (s *Server) IssueConfirm(r *http.Request, scope string) string {
	info := infoFrom(r.Context())
	if info == nil || info.p == nil || !validScope(scope) {
		return ""
	}
	return s.auth.issueConfirm(info.p, scope)
}

// RequireConfirm checks the X-Confirm header of r against scope and uses the id up. It returns
// true when the confirmation is good. Otherwise it has written the answer (428 confirm_required
// when the header is missing, with the scope in X-Confirm-Scope; 403 confirm_invalid when the id
// is unknown, used, expired, from another session or for another scope) and the handler must
// return. Routes that always need a confirmation declare RouteOpts.NeedsConfirm instead; this is
// for a handler that needs one only for some inputs.
func (s *Server) RequireConfirm(w http.ResponseWriter, r *http.Request, scope string) bool {
	id := r.Header.Get(ConfirmHeader)
	if id == "" {
		w.Header().Set("X-Confirm-Scope", scope)
		Error(w, http.StatusPreconditionRequired, "confirm_required", "this action needs a confirmation: obtain an id for the scope and send it as X-Confirm")
		return false
	}
	var p *principal
	if info := infoFrom(r.Context()); info != nil {
		p = info.p
	}
	if err := s.auth.consumeConfirm(p, scope, id); err != nil {
		Error(w, http.StatusForbidden, "confirm_invalid", "the confirmation is unknown, already used, expired or for something else; obtain a new one")
		return false
	}
	return true
}

// Token returns the run token. It exists for Server.URL and for tests of this package family; a
// caller that prints it anywhere but the first line of standard output defeats the design.
func (s *Server) Token() string { return s.auth.currentToken() }

// URL returns the address to open for a server listening on addr: loopback names, the port that
// was bound, and the run token as a query parameter, which the page URL turns into a cookie and
// removes from the address bar. A wildcard bind is spelled localhost.
func (s *Server) URL(addr net.Addr) string {
	host, port := "127.0.0.1", ""
	if ta, ok := addr.(*net.TCPAddr); ok {
		port = strconv.Itoa(ta.Port)
		switch {
		case ta.IP.IsUnspecified():
			host = "localhost"
		case strings.Contains(ta.IP.String(), ":"):
			host = "[" + ta.IP.String() + "]"
		default:
			host = ta.IP.String()
		}
	}
	if port != "" {
		host += ":" + port
	}
	u := url.URL{Scheme: "http", Host: host, Path: "/", RawQuery: "token=" + url.QueryEscape(s.Token())}
	return u.String()
}
