/* 90-views-a.js: the Cache, Mail, Board and Replay views. Each mounts through SL.views.register and owns what it starts.
 * The Cache view follows the agent that was answered last until the person picks one (`f` follows again, PARITY A28); its write
 * column, costs and savings are the server's numbers at list prices. */
(function (SL) {
  'use strict';
  const U = SL.u, { $, $$, esc, mk, sv, fmtK, fmtN, fmtUsd, fmtMs, mmss, clock, tod, hitCls, agCol, pct } = U, D = SL.D, calc = SL.calc, ui = SL.ui = SL.ui || {};
  const reg = SL.views.register;

  /* ======================================================================== CACHE */
  function foldSvg(cp) {
    const W = 360, from = cp.from, to = cp.to; let r = ''; for (let i = 0; i < 5; i++) { const w = 240 * (1 - i / 5 * (1 - to / from)); r += '<rect x="60" y="' + (8 + i * 17) + '" width="' + w.toFixed(1) + '" height="16" fill="var(--rv)" opacity="' + (.85 - i * .1).toFixed(2) + '"/>'; }
    const sw = 240 * to / from;
    return '<svg class="fold-svg" viewBox="0 0 ' + W + ' 150" role="img" aria-label="compaction fold: ' + fmtK(from) + ' to ' + fmtK(to) + ' tokens"><text x="0" y="20" fill="var(--dim)" font-size="10.5" font-family="var(--f-num)">thread</text><text x="0" y="55" fill="var(--dim)" font-size="10.5" font-family="var(--f-num)">fold ↓</text>' + r + '<text x="306" y="20" fill="var(--bright)" font-size="12" font-weight="700" font-family="var(--f-num)">' + fmtK(from) + '</text><rect x="60" y="100" width="' + sw.toFixed(1) + '" height="16" fill="var(--mgr)" opacity=".8"/><text x="' + (60 + sw + 6).toFixed(0) + '" y="113" fill="var(--bright)" font-size="12" font-weight="700" font-family="var(--f-num)">' + fmtK(to) + '</text><text x="0" y="113" fill="var(--dim)" font-size="10.5" font-family="var(--f-num)">spine</text><line x1="60" x2="60" y1="124" y2="142" stroke="var(--bright)" stroke-width="2"/><text x="68" y="138" fill="var(--bright)" font-size="11.5" font-weight="600" font-family="var(--f-num)">resume</text></svg><div class="fold-note"><b>◆ compacted ' + fmtK(from) + ' → ' + fmtK(to) + '</b> <span class="dim">(' + cp.pct + '%)</span> · <span style="color:' + agCol(cp.id) + '">' + cp.id + '</span><em>the cache was warm: a declared, priced rebase</em></div>';
  }
  reg({ name: 'cache', title: 'Cache', mount(sc, root, params, S0) {
    root.innerHTML = '<div class="cache"></div>'; const host = $('.cache', root);
    function render(S, m) {
      if (!m) return; let id = ui.cacheFollow !== false || !ui.cacheAgent || !m.ag[ui.cacheAgent] ? newest(m) : ui.cacheAgent; if (!m.ag[id]) id = 'mgr'; ui.cacheAgent = id;
      const A = m.ag[id], ca = calc.agent(A), col = agCol(id), T = calc.totals(m), st = ui.layerStack(m, id, 38, true), left = calc.warmLeft(m, S.vt), rr = A.ratios, lastR = rr.length ? rr[rr.length - 1] : 0;
      const lastA = m.anomalies.filter(x => x.id === id).slice(-1)[0], expK = lastA ? fmtK(lastA.expected) : fmtK(D.layers.slice(0, 3).reduce((s2, l) => s2 + l.tok, 0)), readN = lastA ? lastA.read : 0;
      const lbl = D.layers.map((l, i) => { const w = st.tot ? D.layerToks(id)[i] / st.tot * 100 : 100 / 6; return '<span style="width:' + w + '%;--lc:' + l.col + '">' + (st.miss && i === 0 ? '⚠' : '') + l.id + (w > 9 ? '<small>' + l.name + '</small>' : '') + '</span>'; }).join('');
      const head = '<section class="panel c-head"><div class="ph"><h2>Its latest prompt</h2><div class="r">' + (ui.cacheFollow !== false ? '<span class="dim" title="the agent answered last; ↑ ↓ choose one, f follows again">following</span>' : '') + '<span>↑ ↓ choose the agent</span><span class="warmtag" style="color:' + (left <= 0 || left < 8 ? 'var(--err)' : 'var(--warm)') + '">● <b class="num" data-warm>' + (left <= 0 ? 'cold' : 'warm ' + clock(left)) + '</b></span></div></div><div class="c-who" style="--c:' + col + '"><b class="id">' + esc(id) + '</b><span class="rl" style="color:' + col + '">' + (id === 'mgr' ? 'manager' : esc(A.role)) + '</span><span class="tt">' + esc(String(A.model || '').split('/').pop()) + '</span><span>' + rr.length + ' requests</span><span class="' + hitCls(ca.pct) + '">' + ca.pct + '% of its prompt read from the cache</span><span class="tt">latest request: <b style="color:var(--fg)">' + Math.round(lastR * 100) + '%</b> read' + (st.miss ? ' (expected the ' + expK + ' shared prefix)' : '') + '</span></div><div style="padding:0 10px">' + ui.layerStack(m, id, 32, true).html + '<div class="layer-labels" style="margin:2px 0 0;padding:0">' + lbl + '</div></div><div class="legend2"><span><i class="sw-read"></i>read from the cache</span><span><i class="sw-paid"></i>paid in full</span><span><i style="background:var(--bright);width:2px"></i>breakpoint (end of the shared prefix G0–G2)</span>' + (st.miss ? '<span class="c-miss" style="margin-left:auto">⚠ cache miss: <span>the harness expected ' + expK + ' read from the cache and got ' + U.fmtN(readN) + '</span></span>' : '<span style="margin-left:auto;color:var(--ok);font:500 12px var(--f-num)">✓ <span style="color:var(--fg2);font-family:var(--f-ui)">the shared prefix was read from the cache</span></span>') + '</div></section>';
      const comps = m.compactions.filter(c => c.id === id), bars = rr.map((r, i) => { const cls = r === 0 ? 'z' : r < .7 ? 'lo' : r < .9 ? 'mid' : '', mk2 = r === 0 ? '<span class="mk" style="color:var(--err)">⚠</span>' : (comps.length && i === rr.length - 1) ? '<span class="mk" style="color:var(--mgr)">◆</span>' : ''; return '<div class="hbar ' + cls + '" title="request ' + (i + 1) + ': ' + Math.round(r * 100) + '%">' + mk2 + '<span class="pc">' + Math.round(r * 100) + '</span><i style="height:' + Math.max(3, r * 100) + '%"></i><span class="nn">' + (i + 1) + '</span></div>'; }).join('');
      const hit = '<section class="panel c-hit"><div class="ph"><h2>Hit ratio per request</h2><div class="r"><span>% of the prompt read</span></div></div><div class="hbars">' + bars + '</div><div class="c-note"><b>' + rr.length + ' requests</b> · overall <b class="' + hitCls(ca.pct) + '">' + ca.pct + '%</b> of its tokens · lowest <b class="' + (rr.length && Math.min.apply(null, rr) === 0 ? 'err' : '') + '">' + (rr.length ? Math.round(Math.min.apply(null, rr) * 100) : 0) + '%</b></div><div class="legend2" style="padding-top:0"><span class="err">⚠ cache break</span><span class="mgr">◆ compaction</span></div></section>';
      const cp = m.compactions[m.compactions.length - 1], fold = '<section class="panel c-fold"><div class="ph"><h2>Compaction</h2><div class="r"><span>' + m.compactions.length + ' so far</span><button class="btn sm" type="button" data-compact>/compact…</button></div></div>' + (cp ? foldSvg(cp) : '<div class="c-note">No compaction yet. When the thread is folded, the fold is drawn here: a declared, priced rebase.</div>') + '</section>';
      const an = m.anomalies, anom = '<section class="panel c-anom"><div class="ph"><h2>Cache anomalies</h2><div class="r"><span>' + an.length + '</span></div></div><div class="anom">' + (an.length ? an.slice().reverse().map(e => '<div class="a"><b>⚠ ' + esc(e.kind) + '</b> <span class="mono" style="display:inline;color:' + agCol(e.id) + '">' + esc(e.id) + '</span><span>read ' + e.read + '/' + fmtK(e.expected) + '<span class="qfull"> · extra ≈ ' + fmtUsd(e.expected * .9 / 1e6, 4) + ' (est.)</span> · ' + ui.todAt(S, e) + '</span><em>' + esc(e.why) + '</em></div>').join('') : '<div class="none">none so far: every request read what the harness expected.</div>') + '<div class="shared"><span class="dim">its prefix · </span>shared <b>' + fmtK(D.layers.slice(0, 3).reduce((s, l) => s + l.tok, 0)) + '</b> tokens of G0–G2 · agents <b>' + (S.roster.length) + '</b><div>joined a warm prefix: its shared layers were read, not written</div></div></div></section>';
      const trs = m.order.map(aid => { const x = m.ag[aid], c = calc.agent(x), r2 = x.ratios, last = r2.length ? Math.round(r2[r2.length - 1] * 100) : 0; return '<tr class="row ' + (aid === id ? 'sel' : '') + '" data-ag="' + esc(aid) + '" data-pick="' + esc(aid) + '" style="--c:' + agCol(aid) + '" tabindex="0" role="button" aria-label="' + esc(aid) + ': choose it"><td class="l id">' + (aid === id ? '› ' : '') + esc(aid) + '</td><td class="l role">' + (aid === 'mgr' ? 'manager' : esc(x.role)) + '</td><td>' + r2.length + '</td><td class="' + hitCls(c.pct) + '">' + c.pct + '%</td><td class="' + (last === 0 && r2.length ? 'err' : hitCls(last)) + '">' + last + '%</td><td>' + fmtN(c.read) + '</td><td>' + fmtN(c.un) + '</td><td class="warm">' + fmtN(c.wr) + '</td><td class="ok qfull">$' + c.saved.toFixed(4) + '</td><td class="opt l"><div class="minis">' + ui.miniStack(m, aid) + '</div></td></tr>'; }).join('');
      const table = '<section class="panel c-table"><div class="ph"><h2>Every agent’s cache</h2><div class="r"><span>read · uncached · write, in tokens</span></div></div><div class="pb" style="overflow:auto;padding-bottom:6px"><table class="ctable"><thead><tr><th>agent</th><th class="l">role</th><th>req</th><th>hit</th><th>last</th><th>read</th><th>uncached</th><th>write</th><th class="qfull">' + ui.savedWord(T) + '</th><th class="opt l">latest prompt, by layer</th></tr></thead><tbody>' + trs + '</tbody><tfoot><tr><td class="l">all</td><td></td><td>' + m.order.reduce((s, x) => s + m.ag[x].ratios.length, 0) + '</td><td title="' + T.hit1 + '%">' + T.pct + '%</td><td></td><td>' + fmtN(T.read) + '</td><td>' + fmtN(T.un) + '</td><td>' + fmtN(T.wr) + '</td><td class="ok qfull">$' + T.saved.toFixed(4) + '</td><td class="opt"></td></tr></tfoot></table></div><div class="price-note">hit = read / (read + uncached): the share of all prompt tokens the agent sent that were read from the cache. last = its latest request alone. <span class="qfull">saved = read tokens × (list input price − cached price) at list prices' + (T.savedPartial ? ' (at least: some reads had no price)' : '') + ': an estimate, not a bill. </span>' + (T.unpriced ? U.fmtN(T.unpriced) + ' tokens at unknown prices are not counted. ' : '') + 'The HUD figure is the same sum over all rows.</div></section>';
      const sum = '<section class="panel c-sum"><div class="ph"><h2>The session</h2><div class="r"><span class="mono">' + esc(S.sid) + '</span></div></div><div class="c-sumtxt"><span><b>' + T.pct + '%</b> <span class="k">of the session’s prompt came from the cache (' + T.hit1 + '%)</span></span><span class="qfull"><span class="k">' + (T.savedPartial ? 'saved at least' : 'saved') + '</span> <b>' + fmtUsd(T.saved, 3) + '</b> <span class="k">(list price, est.)</span></span><span><span class="k">spent</span> <b style="color:var(--warm)">' + fmtUsd(T.cost, 4) + '</b></span><span class="qfull"><span class="k">no cache would have cost</span> ' + fmtUsd(T.cost + T.saved, 3) + ' <span class="k">(est.)</span></span><span><b style="color:var(--mgr)">' + m.compactions.length + '</b> <span class="k">compaction' + (m.compactions.length === 1 ? '' : 's') + '</span></span><span><b style="color:' + (an.length ? 'var(--err)' : 'var(--ok)') + '">' + an.length + '</b> <span class="k">anomal' + (an.length === 1 ? 'y' : 'ies') + '</span></span></div></section>';
      const html = head + hit + fold + anom + table + sum; if (host._h !== html) { const t = root.scrollTop; host._h = html; host.innerHTML = html; root.scrollTop = t; }
    }
    sc.listen(host, 'click', e => { const r = e.target.closest('[data-pick]'); if (r) { ui.cacheAgent = r.dataset.pick; ui.cacheFollow = false; SL.link.select(ui.cacheAgent); host._h = ''; render(SL.sessions.active, SL.sessions.active.m); return; } if (e.target.closest('[data-compact]')) ui.compactDialog(); });
    sc.listen(document, 'keydown', e => { if (e.key === 'f' && !e.ctrlKey && !e.metaKey && !e.altKey && !ui.hasModal() && !e.target.closest('input,textarea,select')) { ui.cacheFollow = true; host._h = ''; const S = SL.sessions.active; render(S, S.m); } });
    sc.listen(host, 'keydown', e => { if (e.key === 'Enter' && e.target.closest('[data-pick]')) e.target.closest('[data-pick]').click(); });
    sc.listen(document, 'keydown', e => { if ((e.key === 'ArrowDown' || e.key === 'ArrowUp') && !ui.hasModal() && !e.target.closest('input,textarea,select')) { const S = SL.sessions.active, ids = S.m.order, i = Math.max(0, ids.indexOf(ui.cacheAgent)), nx = ids[(i + (e.key === 'ArrowDown' ? 1 : ids.length - 1)) % ids.length]; ui.cacheAgent = nx; ui.cacheFollow = false; SL.link.select(nx); host._h = ''; render(S, S.m); e.preventDefault(); } });
    sc.update(render); sc.frame((dt, vt, S) => { const w = $('[data-warm]', root); if (w && S.m) { const left = calc.warmLeft(S.m, vt), t = left <= 0 ? 'cold' : 'warm ' + clock(left); if (w.textContent !== t) w.textContent = t; } });
    sc.onUnmount(() => SL.link.select(null)); render(S0, S0.m);
  } });
  /** The agent that was answered last (the newest request), else the manager. */
  function newest(m) { let best = 'mgr', t = -Infinity; m.order.forEach(id => { const A = m.ag[id]; if (A.ratios.length && A.lastReq > t) { t = A.lastReq; best = id; } }); return best; }
  ui.compactDialog = function () {
    const S = SL.sessions.active, g5 = D.g5.mgr || 0, mm = D.model(S.meta.model), est = g5 && mm && mm.in != null ? fmtUsd(g5 * mm.in / 1e6, 4) : '';
    ui.modal({ title: 'Compact the thread', kicker: '/compact [focus]', desc: 'fold the older thread now; focus says what to keep in view', color: 'var(--mgr)', focus: '#cpIn', body: '<div class="field-row"><input id="cpIn" type="text" placeholder="focus: what to keep in view (optional)" aria-label="Focus"></div><p class="stubnote">This is <b>a declared, priced rebase</b>: the folded thread changes the prompt bytes after G4, so the next request re-reads the shared prefix (warm) and writes the new spine once.' + (est ? ' Estimated extra cost at list prices: <b>' + est + '</b> (est.).' : '') + ' The shared G0–G2 prefix does not change.</p><div class="row2"><button class="btn pri" type="button" id="cpGo">Fold it now</button><button class="btn" type="button" data-close>Cancel</button></div>',
      onMount(b, sc, close) { sc.listen($('#cpGo', b), 'click', () => { const r = SL.act.compact($('#cpIn', b).value.trim()); close(); if (r && r.ok === false) { if (r.why) ui.toast(r.why, 'warm'); return; } ui.toast('compacting the manager’s thread: a declared, priced rebase'); }); sc.listen($('#cpIn', b), 'keydown', e => { if (e.key === 'Enter') $('#cpGo', b).click(); }); } });
  };

  /* ======================================================================== MAIL */
  reg({ name: 'mail', title: 'Mail', mount(sc, root, params, S0) {
    root.innerHTML = '<div class="mailv"><section class="panel flow"><div class="ph"><h2>Who writes to whom</h2><div class="r mcount"></div></div><div class="pb"><svg class="flowsvg" role="img" aria-label="mail between agents"></svg></div></section><section class="panel mail-l"><div class="ph"><h2>Envelopes</h2><div class="r"><span>newest first</span></div></div><div class="mlistv"></div></section><section class="panel"><div class="ph"><h2>Message</h2><div class="r mmeta"></div></div><div class="databan"><span class="ic">✉</span><span>Mail is data, not instructions. It is shown here as text; the receiver reads it as a note from a teammate and it cannot change its permissions or its lease.</span></div><div class="mdetail"></div></section></div>';
    const svg = $('.flowsvg', root), listEl = $('.mlistv', root), det = $('.mdetail', root), env = [];
    let sel = ui.mailSel || null; const W = 1040, BY = 150;
    function xOf(i, n) { const X0 = 56, DX = (W - 2 * X0) / Math.max(1, n - 1); return X0 + i * DX; }
    /** The Mail head: the TUI's counts when the server sends them (PARITY A18), else `N routed · mailman on/off` (D-07). */
    function mailHead(m, S) { const st = m.mailstat, mm = 'mailman ' + (st && st.mailman ? esc(st.mailman) : S.meta.mailman ? 'on' : 'off'); if (!st) return esc(m.mail.length + ' routed · ' + mm); const nd = st.undelivered != null ? st.undelivered : (st.dropped || 0); return (st.sent || 0) + ' sent · ' + (st.delivered || 0) + ' delivered · <span class="' + (nd ? 'warm' : '') + '">' + nd + ' not delivered</span>' + (st.digests ? ' · ' + st.digests + ' digests in ' + (st.batches || 0) + ' batches' : '') + ' · ' + mm; }
    function render(S, m) {
      if (!m) return; const ids = m.order, n = ids.length, ml = m.mail.slice().reverse(); if (!sel || !m.mail.some(x => x.t === sel)) sel = ml.length ? ml[0].t : null; const cur = m.mail.find(x => x.t === sel);
      let arcs = ''; m.mail.forEach(x => { const a = ids.indexOf(x.from), b = ids.indexOf(x.to); if (a < 0 || b < 0) return; const x1 = xOf(a, n), x2 = xOf(b, n), h = 20 + Math.abs(a - b) * 15 - (a > b ? 11 : 0), s = x.t === sel, cy = BY - h * 1.75, d = 'M' + x1 + ' ' + BY + ' Q' + (x1 + x2) / 2 + ' ' + cy + ' ' + x2 + ' ' + BY, mid = BY - h * .87;
        arcs += '<g data-ag="' + esc(x.from) + ' ' + esc(x.to) + '" data-mt="' + esc(x.t) + '" style="cursor:pointer"><path d="' + d + '" fill="none" stroke="' + (s ? 'var(--warm)' : agCol(x.from)) + '" stroke-width="' + (s ? 2.6 : 1.6) + '" opacity="' + (s ? 1 : .7) + '"/><path d="' + d + '" fill="none" stroke="transparent" stroke-width="14"/><text x="' + (x1 + x2) / 2 + '" y="' + (mid + 4) + '" text-anchor="middle" fill="var(--warm)" font-size="14" font-family="var(--f-num)" stroke="var(--panel)" stroke-width="3" paint-order="stroke">✉</text></g>'; });
      const nodes = ids.map((id, i) => '<g data-ag="' + esc(id) + '" transform="translate(' + xOf(i, n) + ' ' + BY + ')" style="cursor:pointer" data-open="' + esc(id) + '"><line y1="0" y2="12" stroke="' + agCol(id) + '" stroke-width="2"/><circle r="6" fill="var(--panel)" stroke="' + agCol(id) + '" stroke-width="2.5"/><text y="30" text-anchor="middle" fill="' + agCol(id) + '" font-size="12" font-weight="700" font-family="var(--f-num)">' + esc(id) + '</text><text y="43" text-anchor="middle" fill="var(--dim)" font-size="10" font-family="var(--f-lab)" letter-spacing="1.4">' + (id === 'mgr' ? 'MANAGER' : esc(String(m.ag[id].role).toUpperCase())) + '</text></g>').join('');
      const html = '<g class="arcs-static">' + arcs + '</g>' + nodes + '<g class="travel"></g>'; svg.setAttribute('viewBox', '0 0 ' + W + ' 200');
      if (svg._h !== html) { svg._h = html; const tr = $('.travel', svg); const keep = tr ? Array.from(tr.childNodes) : []; svg.innerHTML = html; const t2 = $('.travel', svg); keep.forEach(k => t2.appendChild(k)); }
      $('.mcount', root).innerHTML = mailHead(m, S);
      listEl.innerHTML = ml.map(x => '<button class="mitem ' + (x.t === sel ? 'sel' : '') + '" type="button" data-mt="' + esc(x.t) + '" data-ag="' + esc(x.from) + ' ' + esc(x.to) + '"><span class="mi">✉</span><span class="mm"><span class="ml"><span style="color:' + agCol(x.from) + '">' + esc(x.from) + '</span><span class="dim">→</span><span style="color:' + agCol(x.to) + '">' + esc(x.to) + '</span><time>' + ui.todAt(S, x) + (x.tok ? ' · ' + fmtK(x.tok) + ' tok' : '') + '</time></span><span class="mt">“' + esc(x.text) + '”</span></span></button>').join('') || '<div class="c-note">no mail yet</div>';
      const thread = cur ? m.mail.filter(x => (x.from === cur.from && x.to === cur.to) || (x.from === cur.to && x.to === cur.from)) : [];
      det.innerHTML = cur ? '<div class="mailbox"><small>from <b style="color:' + agCol(cur.from) + '">' + esc(cur.from) + '</b> (' + (cur.from === 'mgr' ? 'manager' : m.ag[cur.from] ? esc(m.ag[cur.from].role) : '') + ') · to <b style="color:' + agCol(cur.to) + '">' + esc(cur.to) + '</b> (' + (cur.to === 'mgr' ? 'manager' : m.ag[cur.to] ? esc(m.ag[cur.to].role) : '') + ') · ' + ui.todAt(S, cur) + ' · routed by the harness' + (S.meta.mailman ? ', digested by the mailman' : ', not by a mailman') + '</small>' + esc(cur.text) + '</div><h3 class="lab" style="margin:14px 0 6px">thread between ' + esc(cur.from) + ' and ' + esc(cur.to) + '</h3>' + thread.map(x => '<div class="mrow" style="display:flex"><span class="mt">' + ui.todAt(S, x) + '</span><span class="mf" style="color:' + agCol(x.from) + '">' + esc(x.from) + '</span><span class="mx" style="white-space:normal;font-style:normal;color:var(--fg2)">' + esc(x.text) + '</span></div>').join('') + '<h3 class="lab" style="margin:16px 0 6px">delivery</h3><ul class="plist"><li class="done"><span class="pg">✓</span><span class="pt">written by ' + esc(cur.from) + ' at ' + ui.todAt(S, cur) + '<span class="ps">an agent can write to any teammate; it cannot give another agent permissions</span></span></li><li class="done"><span class="pg">✓</span><span class="pt">' + (/^digest of \d+/.test(cur.text) ? 'digested by the mailman' : 'routed by the harness') + '<span class="ps">no digest agent in the path unless --mailman is on</span></span></li><li class="done"><span class="pg">✓</span><span class="pt">placed in ' + esc(cur.to) + '’s next turn as a quoted note<span class="ps">rendered as text, never as an instruction</span></span></li></ul>' : '<div class="c-note">no message selected</div>';
      $('.mmeta', root).textContent = cur ? ui.todAt(S, cur) : '';
    }
    sc.listen(root, 'click', e => { const x = e.target.closest('[data-mt]'); if (x) { sel = ui.mailSel = +x.dataset.mt; svg._h = ''; render(SL.sessions.active, SL.sessions.active.m); return; } const o = e.target.closest('[data-open]'); if (o) ui.openDrawer(o.dataset.open); });
    /* a travelling envelope for each new mail: transient, inside this view, moved by the sim clock */
    sc.on('ev', ({ ev }) => { if (ev.k !== 'mail' || ui.still()) return; const m = SL.sessions.active.m, ids = m.order, a = ids.indexOf(ev.from), b = ids.indexOf(ev.to); if (a < 0 || b < 0) return; const tr = $('.travel', svg); if (!tr) return; const x1 = xOf(a, ids.length), x2 = xOf(b, ids.length), h = 20 + Math.abs(a - b) * 15, cy = BY - h * 1.75, p = sv('path', { d: 'M' + x1 + ' ' + BY + ' Q' + (x1 + x2) / 2 + ' ' + cy + ' ' + x2 + ' ' + BY, fill: 'none' }, tr), e = sv('text', { class: 'arc-env', 'text-anchor': 'middle' }, tr, '✉'); env.push({ p, e, len: p.getTotalLength(), t: 0 }); });
    sc.frame(dt => { for (let i = env.length - 1; i >= 0; i--) { const v = env[i]; v.t += dt / 1.2; const k = Math.min(1, v.t), pt = v.p.getPointAtLength(v.len * k); v.e.setAttribute('x', pt.x); v.e.setAttribute('y', pt.y + 5); if (k >= 1) { v.p.remove(); v.e.remove(); env.splice(i, 1); } } });
    sc.update(render); render(S0, S0.m);
  } });

  /* ======================================================================== BOARD */
  reg({ name: 'board', title: 'Board', mount(sc, root, params, S0) {
    root.innerHTML = '<div class="boardv"><section class="panel"><div class="ph"><h2>Task board</h2><div class="r"><span class="bbsum"></span><span>drag disabled: the manager moves tasks</span></div></div><div class="kan"></div></section><section class="panel"><div class="ph"><h2>Dependencies</h2><div class="r"><span class="dgsum">a task waits for the tasks it depends on</span></div></div><div class="dg"></div></section></div>';
    const B = ui.board.make(sc, $('.kan', root), true), host = $('.dg', root);
    function render(S, m) {
      if (!m) return; const c = ui.board.update(B, m), bx = ui.boardMarks(B, m); $('.bbsum', root).textContent = (c.merged || 0) + ' merged · ' + (c.verify || 0) + ' verify · ' + (c.running || 0) + ' running · ' + Math.max(0, (c.todo || 0) - m.torder.filter(t => m.tasks[t].failed && m.tasks[t].st === 'todo').length) + ' todo' + ui.boardExtra(bx); ui.alertsSlot($('.bbsum', root), m);
      const ids = m.torder; if (!ids.length) { host.innerHTML = '<div class="c-note">No tasks yet: the manager creates them from the plan.</div>'; return; }
      const W = Math.max(700, host.clientWidth || 900), Hh = Math.max(200, host.clientHeight || 260), nw = 168, nh = 46, P = {};
      const lvl = {}; const lv = id => { if (lvl[id] != null) return lvl[id]; const t = m.tasks[id]; return lvl[id] = t.deps.length ? 1 + Math.max.apply(null, t.deps.filter(d => m.tasks[d]).map(lv).concat([-1])) : 0; }; ids.forEach(lv);
      const maxL = Math.max.apply(null, ids.map(id => lvl[id])) + 1, gx = (W - nw - 24) / Math.max(1, maxL), byL = {}; ids.forEach(id => { (byL[lvl[id]] = byL[lvl[id]] || []).push(id); });
      Object.keys(byL).forEach(L => byL[L].forEach((id, i) => { const k = byL[L].length; P[id] = { x: 12 + L * gx, y: 12 + (k === 1 ? .5 : i / (k - 1)) * (Hh - nh - 24) }; })); P.G = { x: 12 + maxL * gx, y: 12 + .5 * (Hh - nh - 24) };
      const edges = []; ids.forEach(id => m.tasks[id].deps.forEach(d => { if (P[d]) edges.push([d, id]); })); const leaves = ids.filter(id => !ids.some(o => m.tasks[o].deps.includes(id))); leaves.forEach(id => edges.push([id, 'G']));
      const eh = edges.map(([a, b]) => { const A1 = P[a], B1 = P[b], x1 = A1.x + nw, y1 = A1.y + nh / 2, x2 = B1.x, y2 = B1.y + nh / 2, mx = (x1 + x2) / 2, done = a !== 'G' && m.tasks[a].st === 'merged'; return '<path class="ed ' + (done ? 'done' : 'live') + '" d="M' + x1 + ' ' + y1 + ' C' + mx + ' ' + y1 + ' ' + mx + ' ' + y2 + ' ' + (x2 - 6) + ' ' + y2 + '"/><path d="M' + (x2 - 8) + ' ' + (y2 - 4) + ' L' + x2 + ' ' + y2 + ' L' + (x2 - 8) + ' ' + (y2 + 4) + '" fill="none" stroke="' + (done ? 'var(--ok)' : 'var(--warm)') + '" stroke-width="1.6" opacity="' + (done ? .7 : 1) + '"/>'; }).join('');
      const nh2 = Object.keys(P).map(id => { const p = P[id]; if (id === 'G') return '<g class="nd" data-st="' + (m.goal.state === 'met' ? 'merged' : 'todo') + '" transform="translate(' + p.x + ' ' + p.y + ')"><rect width="' + nw + '" height="' + nh + '" rx="2"/><text x="10" y="19">◇ goal</text><text class="sub" x="10" y="35">' + (S.meta.verify ? esc(S.meta.verify.replace('{dirs}', './...')) : 'checks on the merged result') + '</text></g>'; const t = m.tasks[id]; return '<g class="nd" data-st="' + esc(t.st) + '" data-task="' + esc(id) + '" data-ag="' + esc(t.owner || '') + '" transform="translate(' + p.x + ' ' + p.y + ')" style="cursor:pointer" data-open="' + esc(t.owner || '') + '"><rect width="' + nw + '" height="' + nh + '" rx="2"/><text x="10" y="19" fill="' + agCol(t.owner || 'mgr') + '">' + esc(id) + ' <tspan fill="var(--dim)" font-weight="400">' + esc(t.owner || '') + '</tspan></text><text class="sub" x="10" y="35">' + esc(t.title.length > 27 ? t.title.slice(0, 26) + '…' : t.title) + '</text>' + (t.failed ? '<text x="' + (nw - 10) + '" y="19" text-anchor="end" fill="var(--err)"><title>' + esc('failed: ' + (t.closure || 'closed')) + '</title>✗</text>' : t.st === 'merged' ? '<text x="' + (nw - 10) + '" y="19" text-anchor="end" fill="var(--ok)">✓</text>' : t.st === 'verify' ? '<text x="' + (nw - 10) + '" y="19" text-anchor="end" fill="var(--warm)">▸</text>' : '') + '</g>'; }).join('');
      const dh = '<svg viewBox="0 0 ' + W + ' ' + Hh + '" preserveAspectRatio="xMidYMid meet" role="img" aria-label="task dependencies">' + eh + nh2 + '</svg>'; if (host._h !== dh) { host._h = dh; host.innerHTML = dh; }
    }
    sc.listen(host, 'click', e => { const o = e.target.closest('[data-open]'); if (o && o.dataset.open) ui.openDrawer(o.dataset.open); });
    sc.listen(root, 'click', e => { const a = e.target.closest('[data-alerts]'); if (a) { const S = SL.sessions.active; ui.alertsPop(a, S, S.m); } });
    sc.observe(host, () => { host._h = ''; render(SL.sessions.active, SL.sessions.active.m); });
    sc.update(render); render(S0, S0.m);
  } });

  /* ======================================================================== REPLAY */
  function logSegs(S) {
    const ids = S.roster.map(r => r.id), segs = {}; ids.forEach(i => { segs[i] = []; }); const open = {};
    S.log.forEach(e => { if (e.t > S.wt || e.k !== 'state' || !segs[e.id]) return; if (open[e.id]) open[e.id].t1 = e.t; const sg = { s: e.s, t0: e.t, t1: null }; segs[e.id].push(sg); open[e.id] = sg; });
    return segs;
  }
  const NOTABLE = new Set(['mail', 'break', 'compact', 'merge', 'ask', 'answer', 'goal', 'refuse', 'interrupt']);
  function evLabel(e) {
    switch (e.k) { case 'mail': return ['✉', 'var(--warm)', e.from + ' → ' + e.to + ': “' + e.text + '”']; case 'break': return ['⚠', 'var(--err)', 'cache break on ' + e.id + ': ' + e.kind]; case 'compact': return ['◆', 'var(--mgr)', e.id + ' compacted ' + fmtK(e.from) + ' → ' + fmtK(e.to)]; case 'merge': return ['✓', 'var(--ok)', e.id + ' merged (' + e.cmd + ' ✓ ' + fmtMs(e.ms) + ')']; case 'ask': return ['?', 'var(--warm)', e.q.agent + ' asks: ' + e.q.cmd]; case 'answer': return ['❯', 'var(--fe)', 'you answered ' + e.choice]; case 'goal': return ['◇', 'var(--ok)', 'goal ' + e.s]; case 'refuse': return ['⊘', 'var(--err)', e.id + ' refused: ' + e.name + ' ' + (e.arg || '')]; default: return ['⏹', 'var(--warm)', 'interrupt ' + e.id]; }
  }
  reg({ name: 'replay', title: 'Replay', mount(sc, root, params, S0) {
    root.innerHTML = '<div class="replayv"><section class="panel"><div class="ph"><h2>The recorded session</h2><div class="r"><span class="mono sidt"></span><span>events.jsonl · read-only</span></div></div><div class="rp-ctl"><button class="btn" type="button" data-k="home" aria-label="To the start">' + ui.IC.start + '</button><button class="btn" type="button" data-k="back">−10s</button><button class="btn pri rpPlay" type="button" style="min-width:84px"></button><button class="btn" type="button" data-k="fwd">+10s</button><button class="btn" type="button" data-k="end" aria-label="To the end">' + ui.IC.end + '</button><span class="seg" role="group" aria-label="Speed">' + [1, 2, 4].map(s => '<button type="button" data-sp="' + s + '" aria-pressed="false">' + s + 'x</button>').join('') + '</span><span class="num dim rpT" style="margin-left:6px"></span><span style="flex:1"></span><button class="btn live rpLive" type="button" aria-pressed="true">● live</button></div><div class="tape"><svg class="tapeSvg" preserveAspectRatio="none" style="width:100%;cursor:pointer" role="slider" aria-label="Playhead" aria-valuemin="0" tabindex="0"></svg></div></section><div class="rp-grid"><section class="panel"><div class="ph"><h2>Frame</h2><div class="r"><span>what the cockpit shows now</span></div></div><div class="frame rpFrame"></div></section><section class="panel"><div class="ph"><h2>Notable events</h2><div class="r"><span>click to seek</span></div></div><div class="evlist" style="overflow:auto;flex:1;min-height:0"></div></section><section class="panel"><div class="ph"><h2>Keys</h2><div class="r"><span>sleipnir replay</span></div></div><div class="keys"><kbd>space</kbd><span>pause, resume</span><kbd>← →</kbd><span>seek 10 s (shift: a minute)</span><kbd>+ −</kbd><span>speed</span><kbd>home end</kbd><span>start, live</span><kbd>click</kbd><span>the tape seeks</span></div><p class="stubnote" style="padding:0 12px 12px;margin:0">The whole cockpit follows the playhead: open Cockpit and the legs, the clock and the board show that moment. A recording is a function of the log.</p></section></div></div>';
    const svg = $('.tapeSvg', root), W = 1100, X0 = 44; let geo = null, built = '';
    function build(S) {
      const ids = S.roster.map(r => r.id), head = Math.max(S.wt, 40), pps = (W - X0 - 8) / head, Hh = ids.length * 22 + 24, segs = logSegs(S), sig = ids.join() + '|' + Math.round(head / 4) + '|' + S.log.length; if (sig === built) return; built = sig; geo = { pps, X0, W, head };
      svg.setAttribute('viewBox', '0 0 ' + W + ' ' + Hh); svg.style.height = (Hh * 1.1) + 'px'; svg.setAttribute('aria-valuemax', Math.round(head));
      const roles = {}; Object.keys(D.roles).forEach(r => { roles[r] = D.roles[r].code; }); S.roster.forEach(x => { if (!roles[x.role]) roles[x.role] = x.code; });
      let t = '<defs>' + Object.keys(roles).map(r => '<pattern id="rhx-' + esc(r) + '" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="2" height="5" fill="var(--c-' + esc(roles[r]) + ')" opacity=".7"/></pattern>').join('') + '</defs>';
      ids.forEach((id, i) => { const y = 4 + i * 22, role = S.roster[i].role, col = 'var(--c-' + esc(S.roster[i].code) + ')'; t += '<g data-ag="' + esc(id) + '"><text x="0" y="' + (y + 15) + '" fill="' + agCol(id) + '" font-size="11" font-weight="700" font-family="var(--f-num)">' + esc(id) + '</text><line x1="' + X0 + '" x2="' + W + '" y1="' + (y + 20.5) + '" y2="' + (y + 20.5) + '" stroke="var(--line)"/>';
        segs[id].forEach(sg => { const x = X0 + sg.t0 * pps, w = Math.max(1, ((sg.t1 == null ? head : sg.t1) - sg.t0) * pps); if (sg.s === 'think') t += '<rect x="' + x + '" y="' + (y + 3) + '" width="' + w + '" height="14" fill="url(#rhx-' + role + ')" stroke="' + col + '" stroke-opacity=".4"/>'; else if (sg.s === 'tool') t += '<rect x="' + x + '" y="' + (y + 6) + '" width="' + w + '" height="8" fill="' + col + '" opacity=".9"/>'; else if (sg.s === 'edit') t += '<rect x="' + x + '" y="' + (y + 3) + '" width="' + w + '" height="14" fill="' + col + '"/>'; else if (sg.s === 'wait') t += '<rect x="' + (x + .5) + '" y="' + (y + 4) + '" width="' + Math.max(1, w - 1) + '" height="12" fill="none" stroke="' + col + '" stroke-opacity=".7"/>'; else if (sg.s === 'ask') t += '<rect x="' + x + '" y="' + (y + 3) + '" width="' + w + '" height="14" fill="var(--warm)" opacity=".55"/>'; else if (sg.s === 'done') t += '<rect x="' + x + '" y="' + (y + 9) + '" width="' + w + '" height="2" fill="var(--ok)"/>'; }); t += '</g>'; });
      S.log.forEach(e => { if (!NOTABLE.has(e.k) || e.t > S.wt) return; const a = e.id || e.from || (e.q && e.q.agent) || 'mgr', i = Math.max(0, ids.indexOf(a)), [g, c] = evLabel(e); if (e.k === 'goal' || e.k === 'answer') return; t += '<text x="' + (X0 + e.t * pps - 4) + '" y="' + (4 + i * 22 + 13) + '" fill="' + c + '" font-size="11" font-weight="700" stroke="var(--panel)" stroke-width="2.5" paint-order="stroke" font-family="var(--f-num)">' + g + '</text>'; });
      for (let tt = 0; tt <= head; tt += (head > 200 ? 60 : 10)) t += '<text x="' + (X0 + tt * pps) + '" y="' + (Hh - 3) + '" fill="var(--dim)" font-size="9.5" text-anchor="middle" font-family="var(--f-num)">' + mmss(tt) + '</text><line x1="' + (X0 + tt * pps) + '" x2="' + (X0 + tt * pps) + '" y1="0" y2="' + (Hh - 14) + '" stroke="var(--line)" stroke-dasharray="2 4"/>';
      t += '<g class="cur"><line x1="0" x2="0" y1="0" y2="' + (Hh - 14) + '" stroke="var(--fe)" stroke-width="2"/><path d="M-5 0 L5 0 L0 7Z" fill="var(--fe)"/></g>'; svg.innerHTML = t;
      const evs = S.log.filter(e => NOTABLE.has(e.k) && e.t <= S.wt && e.k !== 'answer' && e.k !== 'goal').slice(-14).reverse(); $('.evlist', root).innerHTML = evs.map(e => { const [g, c, tx] = evLabel(e); return '<button class="mrow" type="button" data-seek="' + e.t + '" style="padding:4px 10px"><span class="mt">' + mmss(e.t) + '</span><span style="color:' + c + ';font-family:var(--f-num);font-weight:700;width:14px;text-align:center">' + g + '</span><span class="mx" style="font-style:normal;color:var(--fg2)">' + esc(tx) + '</span></button>'; }).join('');
    }
    function paint(S, m) {
      $('.sidt', root).textContent = S.sid + (S.recorded ? ' · recorded' : ''); const rep = S.replay, playing = !rep || rep.playing; $('.rpPlay', root).innerHTML = (playing ? ui.IC.pause : ui.IC.play) + ' ' + (playing ? 'pause' : 'play'); $$('[data-sp]', root).forEach(b => b.setAttribute('aria-pressed', String(+b.dataset.sp === (rep ? rep.speed : 1)))); $('.rpLive', root).setAttribute('aria-pressed', String(!rep)); build(S);
    }
    function frame(dt, vt, S) {
      if (!geo) return; const cur = $('.cur', svg); if (cur) cur.setAttribute('transform', 'translate(' + (geo.X0 + vt * geo.pps).toFixed(1) + ' 0)'); $('.rpT', root).textContent = mmss(vt) + ' / ' + mmss(S.wt); svg.setAttribute('aria-valuenow', Math.round(vt));
      if (SL.loop.frameNo % 10 === 0 && S.m) { const m = S.m, left = calc.warmLeft(m, vt), T = calc.totals(m), busy = m.order.filter(id => ['think', 'tool', 'edit'].includes(m.ag[id].state)).length; $('.rpFrame', root).innerHTML = '<div class="big">' + mmss(vt) + '</div><div style="margin:8px 0 10px"><span class="dim">' + tod(S.meta.t0, vt) + '</span> · ' + (S.replay ? '<span class="fe">replay</span>' : '<span class="ok">live</span>') + '</div>cost <b>' + fmtUsd(T.cost, 4) + '</b> · hit <b>' + T.pct + '%</b> · prefix <b style="color:' + (left < 8 ? 'var(--err)' : 'var(--warm)') + '">' + (left <= 0 ? 'cold' : 'warm ' + clock(left)) + '</b><br>merged <b>' + m.merged.length + '</b> of ' + m.torder.length + ' · ' + busy + ' working<br>' + (calc.openQuestion(m) ? '<span class="warm">? ' + esc(calc.openQuestion(m).agent) + ' is waiting for an answer</span>' : m.goal.state === 'met' ? '<span class="ok">◇ goal met</span>' : '<span class="dim">nothing waits on you</span>'); }
    }
    const seek = (S, t, play) => { S.seek(t, play); S.touch(); };
    sc.listen(svg, 'click', e => { if (!geo) return; const S = SL.sessions.active, r = svg.getBoundingClientRect(), x = (e.clientX - r.left) / r.width * geo.W; seek(S, (x - geo.X0) / geo.pps, false); });
    sc.listen(svg, 'keydown', e => { const S = SL.sessions.active; if (e.key === 'ArrowLeft') { seek(S, S.vt - 10, false); e.preventDefault(); } else if (e.key === 'ArrowRight') { seek(S, S.vt + 10, false); e.preventDefault(); } });
    sc.listen(root, 'click', e => { const S = SL.sessions.active, k = e.target.closest('[data-k]'), sp = e.target.closest('[data-sp]'), sk = e.target.closest('[data-seek]');
      if (k) { const a = k.dataset.k; if (a === 'home') seek(S, 0, false); else if (a === 'end') { S.goLive(); S.touch(); } else if (a === 'back') seek(S, S.vt - 10, false); else seek(S, S.vt + 10, S.replay ? S.replay.playing : false); }
      else if (sp) { if (!S.replay) S.seek(S.vt, true); S.replay.speed = +sp.dataset.sp; S.replay.playing = true; S.touch(); } else if (sk) seek(S, +sk.dataset.seek - .1, false);
      else if (e.target.closest('.rpPlay')) { if (!S.replay) S.seek(S.vt, false); else S.replay.playing = !S.replay.playing; S.touch(); } else if (e.target.closest('.rpLive')) { S.goLive(); S.touch(); } });
    sc.update(paint); sc.frame(frame); paint(S0, S0.m);
  } });
})(SL);
