/* 91-views-b.js: the Sessions view (live sessions, recorded sessions, prune) and the Settings view (the store round trip). */
(function (SL) {
  'use strict';
  const U = SL.u, { $, $$, esc, fmtUsd, fmtN, mmss, hitCls, agCol } = U, D = SL.D, calc = SL.calc, ui = SL.ui = SL.ui || {}, G = SL.G;
  const reg = SL.views.register, GL = { run: '●', ask: '?', idle: '◌', done: '✓', paused: '⏸' }, WORD = { run: 'running', ask: 'needs you', idle: 'at the prompt', done: 'done', paused: 'paused' };
  const age = s => s < 86400 ? Math.max(1, Math.round(s / 3600)) + 'h' : Math.round(s / 86400) + 'd';
  const thumb = id => { let h = U.hash(id); const r = () => (h = (h * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff, cols = ['var(--mgr)', 'var(--be)', 'var(--fe)', 'var(--sc)', 'var(--ts)']; let o = ''; for (let i = 0; i < 6; i++) { let x = r() * 20; while (x < 146) { const w = 6 + r() * 30; o += '<rect x="' + x.toFixed(1) + '" y="' + i * 5 + '" width="' + Math.min(w, 148 - x).toFixed(1) + '" height="3.5" fill="' + cols[i % 5] + '" opacity="' + (.4 + r() * .5).toFixed(2) + '"/>'; x += w + 3 + r() * 14; } } return '<svg viewBox="0 0 150 30" aria-hidden="true">' + o + '</svg>'; };

  /* ======================================================================== SESSIONS */
  reg({ name: 'sessions', title: 'Sessions', mount(sc, root) {
    root.innerHTML = '<div class="sessv"><section class="panel"><div class="ph"><h2>Live sessions</h2><div class="r"><span class="lcount"></span><button class="btn sm pri" type="button" data-new>+ New session</button></div></div><div class="livecards"></div><div class="ph" style="margin-top:6px"><h2>Recorded</h2><div class="r"><span class="rcount"></span><button class="btn sm" type="button" data-cont>↺ --continue</button></div></div><div class="reclist"></div></section><div class="sess-side"><section class="panel"><div class="ph"><h2>Prune</h2><div class="r"><span class="mono">sessions prune</span></div></div><div class="prune"><p style="margin:0 0 8px">Deletes recorded sessions that are old: the event log, the blobs it points at and the checkpoints of each. The newest are kept whatever their age, and so is any session written to in the last ten minutes. Live sessions are never touched.</p><div class="field-row"><label class="mono" for="pOlder">--older-than</label><input id="pOlder" value="30d" style="max-width:90px"><label class="mono" for="pKeep">--keep</label><input id="pKeep" value="20" style="max-width:70px"></div><pre id="pPre" class="pre"></pre><div class="row2"><button class="btn danger" type="button" id="pYes">Prune with --yes…</button></div><p id="pNote" class="stubnote" style="margin:8px 0 0"></p></div></section><section class="panel"><div class="ph"><h2>Cross-session inbox</h2><div class="r"><span class="nneed"></span></div></div><div class="needs-list"></div></section></div></div>';
    const live = $('.livecards', root), rec = $('.reclist', root);
    function liveHtml() {
      return SL.sessions.list.map(S => { const w = S.wm, c = calc.totals(w), st = S.state(), cur = S === SL.sessions.active, q = calc.openQuestion(w), nW = S.roster.length - 1, merged = w.merged.length, tot = w.torder.length;
        return '<article class="scard' + (cur ? ' cur' : '') + '" data-sid="' + esc(S.id) + '" data-state="' + st + '"><div class="sc-h"><span class="sg">' + GL[st] + '</span><b class="sn">' + esc(S.name) + '</b>' + (cur ? '<span class="tag ok">active</span>' : '') + (S.meta.headless ? '<span class="tag warm" title="nobody can answer: an action that needs approval is refused (--ask-timeout ' + esc(S.meta.askTimeout || '10m') + ')">headless</span>' : '') + (q ? '<span class="tag warm">? needs you</span>' : '') + '<span class="sp"></span><span class="dim">' + WORD[st] + '</span></div><div class="sc-m"><span class="mono">' + esc(S.meta.cwd) + '</span><span>' + esc(S.meta.model.split('/')[1] || S.meta.model) + '</span><span>' + esc(S.meta.mode) + '</span><span>' + (nW ? 'manager + ' + nW + ' workers' : 'single agent') + '</span><span>started ' + esc(S.meta.started || '') + '</span></div><div class="sc-n"><span class="num" data-c="cost">' + fmtUsd(c.cost, 3) + '</span><span class="dim">of ' + (S.meta.budget ? fmtUsd(S.meta.budget, 2) : 'no budget') + '</span><span class="' + hitCls(c.pct) + ' num qfull" data-c="hit">' + c.pct + '% hit</span>' + (tot ? '<span class="num">' + merged + '/' + tot + ' merged</span>' : '') + '</div><div class="gauge wide"><i style="width:' + (S.meta.budget ? Math.min(100, c.cost / S.meta.budget * 100) : 0) + '%"></i></div><pre class="launch mono">' + esc(S.meta.launch || 'sleipnir chat') + '</pre><div class="sc-a"><button class="btn sm pri" type="button" data-open>Open</button><button class="btn sm" type="button" data-ren>Rename</button><button class="btn sm" type="button" data-stop>Stop run</button><button class="btn sm danger" type="button" data-close>Close</button></div></article>'; }).join('');
    }
    function recHtml() { return '<table class="tbl"><thead><tr><th></th><th>session</th><th>first prompt</th><th class="r">agents</th><th class="r">cost</th><th class="r">MB</th><th>age</th><th></th></tr></thead><tbody>' + SL.sessions.recorded.map(r => '<tr><td>' + (r.resumable ? '<span class="res">↺</span>' : '<span class="dim">·</span>') + '</td><td class="mono dim">' + r.id + '</td><td class="bright">' + esc(r.first) + (r.interrupted ? ' <span class="warm">⚠</span>' : '') + '</td><td class="r">' + r.agents + '</td><td class="r">' + fmtUsd(r.cost, 2) + '</td><td class="r">' + r.mb.toFixed(1) + '</td><td>' + age(r.ageS) + '</td><td class="r nowrap"><button class="btn sm pri" type="button" data-res="' + r.id + '"' + (r.resumable ? '' : ' disabled') + '>↺ Resume</button> <button class="btn sm" type="button" data-rep="' + r.id + '">Replay</button></td></tr>').join('') + '</tbody></table>'; }
    function pruneTxt() {
      const o = $('#pOlder', root).value.trim(), k = parseInt($('#pKeep', root).value, 10); const r = SL.sessions.prune(o, isNaN(k) ? 20 : k, false);
      $('#pPre', root).textContent = r.error ? r.error : 'would delete ' + r.list.length + ' session' + (r.list.length === 1 ? '' : 's') + ' (' + r.mb.toFixed(1) + ' MB):\n' + (r.list.map(s => '  ' + s.id + '  ' + age(s.ageS) + '  ' + s.mb.toFixed(1) + ' MB').join('\n') || '  none') + '\n\nnothing is deleted without --yes'; $('#pYes', root).disabled = !!r.error || !r.list.length;
    }
    let sig = '';
    function render() {
      const s2 = SL.sessions.list.map(S => S.id + S.name + S.state() + S.meta.mode + S.meta.model + S.meta.swarm + (S === SL.sessions.active)).join('|') + '#' + SL.sessions.recorded.length + '#' + SL.sessions.needs().length;
      if (s2 !== sig) { sig = s2; live.innerHTML = liveHtml(); rec.innerHTML = recHtml(); pruneTxt(); const nd = SL.sessions.needs(); $('.nneed', root).textContent = nd.length + ' open'; $('.needs-list', root).innerHTML = nd.length ? nd.map(({ S, q }) => '<div class="nrow"><b style="color:var(--c-mgr)">' + esc(S.name) + '</b> › <span style="color:' + agCol(q.agent) + '">' + esc(q.agent) + '</span> <span class="mono">' + esc(q.cmd) + '</span><button class="btn sm" type="button" data-inb>Answer…</button></div>').join('') : '<p class="stubnote" style="padding:10px 12px;margin:0">Nothing waits for you in any session.</p>'; $('.lcount', root).textContent = SL.sessions.list.length + ' running'; $('.rcount', root).textContent = SL.sessions.recorded.length + ' · ' + SL.sessions.recordedMb().toFixed(1) + ' MB on disk'; }
      $$('.scard', live).forEach(c => { const S = SL.sessions.get(c.dataset.sid); if (!S) return; const t = calc.totals(S.wm), e = $('[data-c="cost"]', c), h = $('[data-c="hit"]', c); if (e) { const x = fmtUsd(t.cost, 3); if (e.textContent !== x) e.textContent = x; } if (h) { const x = t.pct + '% hit'; if (h.textContent !== x) h.textContent = x; } });
    }
    sc.listen(root, 'click', e => { const t = e.target, card = t.closest('.scard'), S = card && SL.sessions.get(card.dataset.sid);
      if (t.closest('[data-new]')) ui.dialogs.newSession(); else if (t.closest('[data-cont]')) { const r = SL.act.resumeSession('latest'); if (r && r.ok === false) ui.toast(r.why, 'warm'); }
      else if (S && t.closest('[data-open]')) { SL.act.switchSession(S.id); } else if (S && t.closest('[data-ren]')) ui.dialogs.rename(S);
      else if (S && t.closest('[data-stop]')) { SL.act.switchSession(S.id); ui.sessionMenu && ui.confirm({ title: 'Stop the run', text: 'Stop <b>' + esc(S.name) + '</b>? Every agent is interrupted and the goal is paused.', ok: 'Stop the run', danger: true, run: () => { const r = SL.act.interrupt('turn', S.id); ui.toast(r.ok ? 'stopped: the goal is paused' : (r.why || 'nothing was running'), 'warm'); } }); }
      else if (S && t.closest('[data-close]')) ui.confirm({ title: 'Close the session', text: 'Close <b>' + esc(S.name) + '</b>? Its team stops and the tab goes away. The recorded log stays on disk and can be resumed with ↺.', ok: 'Close it', danger: true, run: () => { if (SL.sessions.list.length < 2) { ui.toast('the last session cannot be closed: start another first', 'warm'); return; } SL.act.closeSession(S.id); ui.toast('closed ' + S.name); } });
      else if (t.closest('[data-res]')) { const r = SL.act.resumeSession(t.closest('[data-res]').dataset.res); if (r && r.ok === false) ui.toast(r.why, 'warm'); else ui.toast('resumed', 'ok'); }
      else if (t.closest('[data-rep]')) { SL.views.show('replay'); ui.toast('the recorded session shown is the one in this page (mock)', 'warm'); } else if (t.closest('[data-inb]')) ui.inbox.toggle($('#sInbox'));
      else if (t.closest('#pYes')) { const o = $('#pOlder', root).value.trim(), k = parseInt($('#pKeep', root).value, 10), r = SL.sessions.prune(o, isNaN(k) ? 20 : k, false); if (r.error || !r.list.length) return; ui.confirm({ title: 'Prune with --yes', text: 'Delete <b>' + r.list.length + '</b> recorded session' + (r.list.length === 1 ? '' : 's') + ' (' + r.mb.toFixed(1) + ' MB): the event log, its blobs and its checkpoints?', detail: '<span class="mono">' + esc(r.list.map(s => s.id).join('\n')) + '</span>', ok: 'Delete them', danger: true, run: () => { const a = SL.sessions.prune(o, isNaN(k) ? 20 : k, true); $('#pNote', root).textContent = 'deleted ' + a.list.length + ' session' + (a.list.length === 1 ? '' : 's') + ', freed ' + a.mb.toFixed(1) + ' MB'; ui.toast('pruned ' + a.list.length + ' sessions, ' + a.mb.toFixed(1) + ' MB freed', 'ok'); } }); } });
    sc.listen(root, 'input', e => { if (e.target.id === 'pOlder' || e.target.id === 'pKeep') pruneTxt(); });
    sc.on('recorded-changed', () => { sig = ''; render(); }); sc.on('sessions-changed', () => { sig = ''; render(); }); sc.on('needs-changed', () => { sig = ''; });
    sc.update(render); sc.frame(() => { if (SL.loop.frameNo % 30 === 0) render(); }); render();
  } });

})(SL);
