package repocheck

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type functionDocumentation struct {
	total, documented int
	missing           []string
}

// scanFunctionDocumentation counts named Go functions and methods in source
// directories, including every platform variant without evaluating build tags.
func scanFunctionDocumentation(base string, dirs ...string) (functionDocumentation, error) {
	var result functionDocumentation
	positions := token.NewFileSet()
	for _, dir := range dirs {
		err := filepath.WalkDir(filepath.Join(base, dir), func(path string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				if entry.Name() == "testdata" || entry.Name() == "vendor" || strings.HasPrefix(entry.Name(), ".") {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			file, err := parser.ParseFile(positions, path, nil, parser.ParseComments)
			if err != nil {
				return err
			}
			if ast.IsGenerated(file) {
				return nil
			}
			for _, declaration := range file.Decls {
				function, ok := declaration.(*ast.FuncDecl)
				if !ok {
					continue
				}
				result.total++
				if function.Doc != nil && strings.TrimSpace(function.Doc.Text()) != "" {
					result.documented++
					continue
				}
				rel, err := filepath.Rel(base, path)
				if err != nil {
					return err
				}
				result.missing = append(result.missing, fmt.Sprintf("%s:%d: %s", filepath.ToSlash(rel), positions.Position(function.Pos()).Line, function.Name.Name))
			}
			return nil
		})
		if err != nil {
			return result, err
		}
	}
	return result, nil
}

// TestProductionDocCoverage enforces the repository's documentation floor for
// production declarations. Comment accuracy remains a code-review responsibility.
func TestProductionDocCoverage(t *testing.T) {
	coverage, err := scanFunctionDocumentation(root(t), "cmd", "internal")
	if err != nil {
		t.Fatal(err)
	}
	if coverage.total == 0 {
		t.Fatal("no production functions found")
	}
	percent := 100 * float64(coverage.documented) / float64(coverage.total)
	t.Logf("production Go doc comments: %d/%d (%.2f%%); minimum 90%%", coverage.documented, coverage.total, percent)
	if coverage.documented*10 < coverage.total*9 {
		for _, missing := range coverage.missing[:min(25, len(coverage.missing))] {
			t.Log(missing)
		}
		t.Fatalf("documentation coverage %.2f%% is below 90%%; %d declarations lack doc comments", percent, len(coverage.missing))
	}
}

func TestFunctionDocumentationScope(t *testing.T) {
	base := t.TempDir()
	files := map[string]string{
		"cmd/main.go":                          "package main\n// main starts the command.\nfunc main() {}\n",
		"internal/example/value.go":            "package example\n// Value is documented.\nfunc Value() int { return 1 }\nfunc private() {}\ntype T struct{}\n// Read returns a value.\nfunc (T) Read() {}\n",
		"internal/example/platform_windows.go": "//go:build windows\n\npackage example\nfunc platform() {}\n",
		"internal/example/empty.go":            "package example\n//\nfunc empty() {}\n//go:noinline\nfunc directiveOnly() {}\nvar callback = func() {}\n",
		"internal/example/value_test.go":       "not parsed: test fixture",
		"internal/example/generated.go":        "// Code generated by fixture. DO NOT EDIT.\npackage example\nfunc Generated() {}\n",
		"internal/example/testdata/broken.go":  "not parsed: test fixture",
		"internal/example/vendor/broken.go":    "not parsed: vendored fixture",
		"internal/example/.hidden/broken.go":   "not parsed: hidden fixture",
	}
	for name, contents := range files {
		path := filepath.Join(base, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	coverage, err := scanFunctionDocumentation(base, "cmd", "internal")
	if err != nil {
		t.Fatal(err)
	}
	if coverage.total != 7 || coverage.documented != 3 || len(coverage.missing) != 4 {
		t.Fatalf("wrong declaration counts: %+v", coverage)
	}
	if !strings.Contains(strings.Join(coverage.missing, "\n"), "platform_windows.go") {
		t.Fatal("host platform changed the coverage denominator")
	}
}
