// Command stdmini builds the benchmark's Go corpus: a module named "stdmini" made of copies of self-contained packages
// from the Go standard library (their tests and testdata included), with the imports between the copies rewritten so the
// module stands alone. Real, well-tested, unfamiliar-in-shape code, without committing any of it: the copies are made from
// the local GOROOT at build time, so the corpus is identified by the Go version and the tree hash printed at the end.
//
//	go run ./bench/tools/stdmini --out DIR [--packages bench/stdmini/packages.txt] [--no-verify]
//
// The result is a git repository with one commit whose author, date and message are fixed, so the same Go version always
// yields the same commit id. Verification builds and tests every package in it; a package that does not pass is an error
// (the list is pinned, a Go release that changes a package is meant to be noticed), never silently dropped.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Fixed so that the commit id depends only on the content.
const (
	commitDate   = "2020-01-01T00:00:00Z"
	commitAuthor = "stdmini"
	commitMail   = "stdmini@example.invalid"
	commitMsg    = "stdmini: self-contained standard library packages, imports rewritten\n"
)

const readme = `# stdmini

Copies of self-contained packages from the Go standard library, with the imports between them rewritten to this module.
Generated by bench/tools/stdmini from the local GOROOT; not the upstream tree. The code is under the Go project's BSD
licence (see LICENSE).
`

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "stdmini:", err)
		os.Exit(1)
	}
}

type options struct {
	out, list, module, goroot string
	verify                    bool
}

func run(args []string, stdout, stderr io.Writer) error {
	fs := flag.NewFlagSet("stdmini", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var o options
	fs.StringVar(&o.out, "out", "", "directory to create (must not exist or be empty)")
	fs.StringVar(&o.list, "packages", "bench/stdmini/packages.txt", "file listing the standard library packages to copy, one import path per line")
	fs.StringVar(&o.module, "module", "stdmini", "module path of the result")
	fs.StringVar(&o.goroot, "goroot", "", "GOROOT to copy from (default: go env GOROOT)")
	fs.BoolVar(&o.verify, "verify", true, "build and test every package of the result")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if o.out == "" {
		return errors.New("--out is required")
	}
	pkgs, err := readList(o.list)
	if err != nil {
		return err
	}
	root, err := build(o, pkgs)
	if err != nil {
		return err
	}
	sum, n, err := treeHash(root)
	if err != nil {
		return err
	}
	rev, err := gitOut(root, "rev-parse", "HEAD")
	if err != nil {
		return err
	}
	goVer, _ := exec.Command("go", "env", "GOVERSION").Output()
	fmt.Fprintf(stdout, "stdmini: %d packages, %d files, go %s\ntree_sha256 %s\ncommit %s\n", len(pkgs), n, strings.TrimSpace(string(goVer)), sum, strings.TrimSpace(rev))
	return nil
}

// entry is one line of the package list: an import path, and files of that package that are left out ("!name"), for the
// few test files that import a standard library package which itself imports a listed one (two copies of a type do not
// unify).
type entry struct {
	path    string
	exclude map[string]bool
}

// readList reads a package list: one entry a line, # comments, sorted and de-duplicated by import path.
func readList(file string) ([]entry, error) {
	raw, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var out []entry
	for _, line := range strings.Split(string(raw), "\n") {
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		e := entry{path: fields[0], exclude: map[string]bool{}}
		for _, f := range fields[1:] {
			if !strings.HasPrefix(f, "!") || strings.ContainsAny(f, "/\\") {
				return nil, fmt.Errorf("%s: %q: after the import path only !file names are allowed", file, strings.TrimSpace(line))
			}
			e.exclude[strings.TrimPrefix(f, "!")] = true
		}
		if seen[e.path] {
			return nil, fmt.Errorf("%s lists %s twice", file, e.path)
		}
		seen[e.path] = true
		out = append(out, e)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s lists no package", file)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].path < out[j].path })
	return out, nil
}

type listed struct {
	ImportPath string
	Dir        string
	Standard   bool
}

// build writes the corpus into o.out and commits it; it returns the directory.
func build(o options, entries []entry) (string, error) {
	pkgs := make([]string, len(entries))
	exclude := map[string]map[string]bool{}
	for i, e := range entries {
		pkgs[i] = e.path
		exclude[e.path] = e.exclude
	}
	if entries, err := os.ReadDir(o.out); err == nil && len(entries) > 0 {
		return "", fmt.Errorf("%s exists and is not empty", o.out)
	}
	root, err := filepath.Abs(o.out)
	if err != nil {
		return "", err
	}
	infos, err := goList(pkgs)
	if err != nil {
		return "", err
	}
	selected := map[string]bool{}
	for _, p := range pkgs {
		selected[p] = true
	}
	for _, in := range infos {
		if !in.Standard {
			return "", fmt.Errorf("%s is not a standard library package", in.ImportPath)
		}
	}
	if len(infos) != len(pkgs) {
		return "", fmt.Errorf("go list found %d of %d packages", len(infos), len(pkgs))
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return "", err
	}
	for _, in := range infos {
		if err := copyPackage(in.Dir, filepath.Join(root, filepath.FromSlash(in.ImportPath)), o.module, selected, exclude[in.ImportPath]); err != nil {
			return "", fmt.Errorf("%s: %w", in.ImportPath, err)
		}
	}
	goroot := o.goroot
	if goroot == "" {
		b, err := exec.Command("go", "env", "GOROOT").Output()
		if err != nil {
			return "", err
		}
		goroot = strings.TrimSpace(string(b))
	}
	if lic, err := os.ReadFile(filepath.Join(goroot, "LICENSE")); err == nil {
		if err := os.WriteFile(filepath.Join(root, "LICENSE"), lic, 0o644); err != nil {
			return "", err
		}
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module "+o.module+"\n\ngo 1.24\n"), 0o644); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte(readme), 0o644); err != nil {
		return "", err
	}
	if err := commit(root); err != nil {
		return "", err
	}
	if o.verify {
		if err := verify(root); err != nil {
			return "", err
		}
	}
	return root, nil
}

func goList(pkgs []string) ([]listed, error) {
	cmd := exec.Command("go", append([]string{"list", "-json=ImportPath,Dir,Standard"}, pkgs...)...)
	cmd.Env = cleanEnv()
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %v\n%s", err, stderr.String())
	}
	var res []listed
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var l listed
		if err := dec.Decode(&l); err != nil {
			return nil, err
		}
		res = append(res, l)
	}
	sort.Slice(res, func(i, j int) bool { return res[i].ImportPath < res[j].ImportPath })
	return res, nil
}

// cleanEnv is the environment of the go commands run here: the toolchain in PATH, no network, no toolchain switching.
func cleanEnv() []string {
	env := os.Environ()
	env = append(env, "GOTOOLCHAIN=local", "GOFLAGS=-mod=mod", "GOWORK=off", "GOPROXY=off")
	return env
}

// copyPackage copies one package directory: its files, and its testdata tree. Child packages are not copied; a child that
// is wanted is listed on its own. Go files outside testdata have their imports of selected packages rewritten.
func copyPackage(src, dst string, module string, selected, exclude map[string]bool) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	for _, e := range entries {
		from := filepath.Join(src, e.Name())
		to := filepath.Join(dst, e.Name())
		switch {
		case exclude[e.Name()]:
			continue
		case e.IsDir() && e.Name() == "testdata":
			if err := copyTree(from, to); err != nil {
				return err
			}
		case e.IsDir():
			continue
		case !e.Type().IsRegular():
			continue
		case strings.HasSuffix(e.Name(), ".go"):
			body, err := os.ReadFile(from)
			if err != nil {
				return err
			}
			body, err = rewriteImports(e.Name(), body, module, selected)
			if err != nil {
				return err
			}
			if err := os.WriteFile(to, body, 0o644); err != nil {
				return err
			}
		default:
			if err := copyFile(from, to); err != nil {
				return err
			}
		}
	}
	return nil
}

func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		to := filepath.Join(dst, rel)
		switch {
		case d.IsDir():
			return os.MkdirAll(to, 0o755)
		case d.Type().IsRegular():
			return copyFile(p, to)
		}
		return nil // symlinks and devices are not corpus
	})
}

func copyFile(from, to string) error {
	b, err := os.ReadFile(from)
	if err != nil {
		return err
	}
	return os.WriteFile(to, b, 0o644)
}

// rewriteImports replaces, byte for byte, the quoted path of every import of a selected package with module/path, then
// lets gofmt re-sort the import block. A file with no such import is returned unchanged.
func rewriteImports(name string, src []byte, module string, selected map[string]bool) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, name, src, parser.ImportsOnly|parser.ParseComments)
	if err != nil {
		return nil, err
	}
	type edit struct {
		from, to int
		text     string
	}
	var edits []edit
	for _, imp := range f.Imports {
		p, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			return nil, err
		}
		if !selected[path.Clean(p)] {
			continue
		}
		edits = append(edits, edit{fset.Position(imp.Path.Pos()).Offset, fset.Position(imp.Path.End()).Offset, strconv.Quote(module + "/" + p)})
	}
	if len(edits) == 0 {
		return src, nil
	}
	sort.Slice(edits, func(i, j int) bool { return edits[i].from > edits[j].from })
	out := append([]byte(nil), src...)
	for _, e := range edits {
		out = append(out[:e.from], append([]byte(e.text), out[e.to:]...)...)
	}
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("%s: gofmt after rewriting imports: %w", name, err)
	}
	return formatted, nil
}

func git(dir string, args ...string) error {
	_, err := gitOut(dir, args...)
	return err
}

func gitOut(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", append([]string{"-c", "core.autocrlf=false", "-c", "commit.gpgsign=false", "-c", "init.defaultBranch=main"}, args...)...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_NAME="+commitAuthor, "GIT_AUTHOR_EMAIL="+commitMail, "GIT_AUTHOR_DATE="+commitDate,
		"GIT_COMMITTER_NAME="+commitAuthor, "GIT_COMMITTER_EMAIL="+commitMail, "GIT_COMMITTER_DATE="+commitDate,
		"GIT_CONFIG_GLOBAL=/dev/null", "GIT_CONFIG_SYSTEM=/dev/null")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %v\n%s", strings.Join(args, " "), err, stderr.String())
	}
	return string(out), nil
}

func commit(root string) error {
	if err := git(root, "init", "-q"); err != nil {
		return err
	}
	if err := git(root, "add", "-A"); err != nil {
		return err
	}
	return git(root, "commit", "-q", "-m", strings.TrimSuffix(commitMsg, "\n"))
}

// verify builds the module and runs every package's tests once.
func verify(root string) error {
	for _, args := range [][]string{{"build", "./..."}, {"vet", "./..."}, {"test", "-count=1", "./..."}} {
		cmd := exec.Command("go", args...)
		cmd.Dir = root
		cmd.Env = cleanEnv()
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("go %s in the corpus failed: %v\n%s", strings.Join(args, " "), err, tail(string(out), 4000))
		}
	}
	return nil
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return "...\n" + s[len(s)-n:]
}

// treeHash hashes the file names and contents of a directory, without .git: the identity of the corpus that does not
// depend on git's object format or the machine.
func treeHash(root string) (string, int, error) {
	var names []string
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && d.Name() == ".git" {
			return fs.SkipDir
		}
		if d.Type().IsRegular() {
			rel, _ := filepath.Rel(root, p)
			names = append(names, filepath.ToSlash(rel))
		}
		return nil
	})
	if err != nil {
		return "", 0, err
	}
	sort.Strings(names)
	h := sha256.New()
	for _, n := range names {
		b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(n)))
		if err != nil {
			return "", 0, err
		}
		s := sha256.Sum256(b)
		fmt.Fprintf(h, "%s %x\n", n, s)
	}
	return hex.EncodeToString(h.Sum(nil)), len(names), nil
}
