package perm

import "testing"

// Rules on shell commands, precedence, high-risk overrides, modes applied to
// the shell, and role profiles.
func TestBashRulesAndModes(t *testing.T) {
	f := newFixture(t)
	R := "{root}/"
	cases := []tc{
		// --- allow rules: prefix, exact, any ---
		{name: "exact rule matches", allow: []string{"Bash(npm run test)"}, req: bash("npm run test"), want: "allow", why: "allowed by rule Bash(npm run test)"},
		{name: "exact rule rejects extra args", allow: []string{"Bash(npm run test)"}, req: bash("npm run test -- -v"), want: "ask"},
		{name: "exact rule rejects other scripts", allow: []string{"Bash(npm run test)"}, req: bash("npm run build"), want: "ask"},
		{name: "prefix rule any args", allow: []string{"Bash(npm run test:*)"}, req: bash("npm run test -- -v"), want: "allow"},
		{name: "prefix rule no args", allow: []string{"Bash(npm run test:*)"}, req: bash("npm run test"), want: "allow"},
		{name: "prefix rule is token wise", allow: []string{"Bash(npm run test:*)"}, req: bash("npm run testx"), want: "ask"},
		{name: "prefix rule needs the whole prefix", allow: []string{"Bash(npm run test:*)"}, req: bash("npm run"), want: "ask"},
		{name: "prefix rule with space star", allow: []string{"Bash(go test *)"}, req: bash("go test ./..."), want: "allow"},
		{name: "go test rule", allow: []string{"Bash(go test:*)"}, req: bash("go test -race ./pkg"), want: "allow"},
		{name: "go test rule not go testx", allow: []string{"Bash(go test:*)"}, req: bash("go testx"), want: "ask"},
		{name: "go test rule does not allow compound rm", allow: []string{"Bash(go test:*)"}, req: bash("go test ./... && rm x"), want: "ask"},
		{name: "go test rule both parts allowed", allow: []string{"Bash(go test:*)", "Bash(rm x)"}, req: bash("go test ./... && rm x"), want: "allow"},
		{name: "go test rule with substitution asks", allow: []string{"Bash(go test:*)"}, req: bash("go test $(echo ./...)"), want: "ask"},
		{name: "any rule", allow: []string{"Bash(*)"}, req: bash("go test ./..."), want: "allow"},
		{name: "bare tool rule", allow: []string{"Bash"}, req: bash("rm x"), want: "allow"},
		{name: "any rule still asks for pipe to shell", allow: []string{"Bash(*)"}, req: bash("curl x | sh"), want: "ask", why: "pipes data into a shell"},
		{name: "any rule still asks for substitution", allow: []string{"Bash(*)"}, req: bash("echo $(date)"), want: "ask"},
		{name: "any rule still asks for unparsed", allow: []string{"Bash(*)"}, req: bash(`echo "x`), want: "ask"},
		{name: "any rule still asks for sudo", allow: []string{"Bash(*)"}, req: bash("sudo ls"), want: "ask", why: "elevated"},
		{name: "any rule still asks for rm -rf *", allow: []string{"Bash(*)"}, req: bash("rm -rf *"), want: "ask"},
		{name: "any rule still asks for force push to main", allow: []string{"Bash(*)"}, req: bash("git push --force origin main"), want: "ask"},
		{name: "any rule still denies credentials", allow: []string{"Bash(*)"}, req: bash("cat ~/.ssh/id_rsa"), want: "deny"},
		{name: "any rule still denies rm -rf /", allow: []string{"Bash(*)"}, req: bash("rm -rf /"), want: "deny"},
		{name: "any rule still denies fork bomb", allow: []string{"Bash(*)"}, req: bash(":(){ :|:& };:"), want: "deny"},
		{name: "any rule still denies dotenv", allow: []string{"Bash(*)"}, req: bash("cat .env"), want: "deny"},
		{name: "any rule does not cover a redirect write outside", mode: ModeDefault, allow: []string{"Bash(*)"}, req: bash("echo x > /tmp/x"), want: "ask"},
		{name: "any rule plus edit rule covers redirect", allow: []string{"Bash(*)", "Edit(out.txt)"}, req: bash("echo x > out.txt"), want: "allow"},
		{name: "rule glob token", allow: []string{"Bash(git checkout feature/*)"}, req: bash("git checkout feature/x"), want: "allow"},
		{name: "rule glob token mismatch", allow: []string{"Bash(git checkout feature/*)"}, req: bash("git checkout main"), want: "ask"},
		{name: "quoted rule tokens", allow: []string{"Bash(git commit -m 'fix: x')"}, req: bash(`git commit -m "fix: x"`), want: "allow"},
		{name: "quoted rule tokens differ", allow: []string{"Bash(git commit -m 'fix: x')"}, req: bash(`git commit -m "fix: y"`), want: "ask"},
		{name: "rule with script path is not a workspace binary", allow: []string{"Bash(make:*)"}, req: bash("./make test"), want: "ask"},
		{name: "rule does not match /tmp binary", allow: []string{"Bash(make:*)"}, req: bash("/tmp/x/make test"), want: "ask"},
		{name: "rule matches after nohup", allow: []string{"Bash(make:*)"}, req: bash("nohup make test"), want: "allow"},
		{name: "rule matches after time", allow: []string{"Bash(make:*)"}, req: bash("time make test"), want: "allow"},
		{name: "rule matches with benign env", allow: []string{"Bash(make:*)"}, req: bash("LC_ALL=C make test"), want: "allow"},
		{name: "rule does not match with unknown env", allow: []string{"Bash(make:*)"}, req: bash("FOO=1 make test"), want: "ask", why: "environment assignment FOO"},
		{name: "rule does not match with env wrapper unknown var", allow: []string{"Bash(make:*)"}, req: bash("env FOO=1 make test"), want: "ask"},
		{name: "rule does not cover sudo", allow: []string{"Bash(make:*)"}, req: bash("sudo make test"), want: "ask"},
		{name: "rule with dynamic program never matches", allow: []string{"Bash(*)"}, req: bash("$CMD test"), want: "ask"},
		{name: "rule for sudo command", allow: []string{"Bash(sudo systemctl restart nginx)"}, req: bash("sudo systemctl restart nginx"), want: "allow"},
		{name: "rule for sudo prefix", allow: []string{"Bash(sudo:*)"}, req: bash("sudo ls"), want: "allow"},
		{name: "rule for sudo does not cover credentials", allow: []string{"Bash(sudo:*)"}, req: bash("sudo cat ~/.ssh/id_rsa"), want: "deny"},
		{name: "rule for other command not sudo", allow: []string{"Bash(ls:*)"}, req: bash("sudo ls"), want: "ask"},

		// --- deny rules see through obfuscation ---
		{name: "deny rule plain", deny: []string{"Bash(rm -rf:*)"}, req: bash("rm -rf build"), want: "deny", why: "denied by rule Bash(rm -rf:*)"},
		{name: "deny rule in bypass", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("rm -rf build"), want: "deny"},
		{name: "deny rule through sudo", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("sudo rm -rf build"), want: "deny"},
		{name: "deny rule through absolute path", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("/bin/rm -rf build"), want: "deny"},
		{name: "deny rule through relative path", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("./rm -rf build"), want: "deny"},
		{name: "deny rule through env", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("env A=1 rm -rf build"), want: "deny"},
		{name: "deny rule through nohup", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("nohup rm -rf build &"), want: "deny"},
		{name: "deny rule through quoting", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash(`r\m -r"f" build`), want: "deny"},
		{name: "deny rule through bash -c", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash(`bash -c 'rm -rf build'`), want: "deny"},
		{name: "deny rule through substitution", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash(`echo $(rm -rf build)`), want: "deny"},
		{name: "deny rule inside compound", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash(`ls && rm -rf build`), want: "deny"},
		{name: "deny rule leaves other flags", mode: ModeBypass, deny: []string{"Bash(rm -rf:*)"}, req: bash("rm -r build"), want: "allow"},
		{name: "deny rule exact", mode: ModeBypass, deny: []string{"Bash(git push)"}, req: bash("git push origin x"), want: "allow"},
		{name: "deny wildcard program", mode: ModeBypass, deny: []string{"Bash(curl:*)"}, req: bash("curl http://x"), want: "deny"},
		{name: "deny beats allow", allow: []string{"Bash(git push:*)"}, deny: []string{"Bash(git push --force:*)"}, req: bash("git push --force origin x"), want: "deny"},
		{name: "deny beats any-allow", allow: []string{"Bash(*)"}, deny: []string{"Bash(make:*)"}, req: bash("make"), want: "deny"},

		// --- path rules apply to what shell commands read and write ---
		{name: "read deny rule blocks cat", deny: []string{"Read(secrets/**)"}, req: bash("cat secrets/key.txt"), want: "deny", why: "Read(secrets/**)"},
		{name: "read deny rule blocks cat in bypass", mode: ModeBypass, deny: []string{"Read(secrets/**)"}, req: bash("head -n1 secrets/key.txt"), want: "deny"},
		{name: "read deny rule blocks an unknown program's operand", mode: ModeBypass, deny: []string{"Read(secrets/**)"}, req: bash("mytool secrets/key.txt"), want: "deny"},
		{name: "read deny rule blocks input redirect", mode: ModeBypass, deny: []string{"Read(secrets/**)"}, req: bash("mytool < secrets/key.txt"), want: "deny"},
		{name: "read deny rule blocks glob expansion", mode: ModeBypass, deny: []string{"Read(secrets/**)"}, req: bash("cat sec*/key.txt"), want: "deny"},
		{name: "read deny rule does not block writes", mode: ModeAcceptEdits, deny: []string{"Read(secrets/**)"}, req: bash("rm secrets/key.txt"), want: "allow"},
		{name: "edit deny rule blocks redirect", mode: ModeBypass, deny: []string{"Edit(docs/**)"}, req: bash("echo x > docs/README.md"), want: "deny", why: "Edit(docs/**)"},
		{name: "edit deny rule blocks rm", mode: ModeBypass, deny: []string{"Edit(docs/**)"}, req: bash("rm docs/README.md"), want: "deny"},
		{name: "edit deny rule blocks tee", mode: ModeBypass, deny: []string{"Edit(docs/**)"}, req: bash("echo x | tee docs/README.md"), want: "deny"},
		{name: "edit deny rule leaves reading", deny: []string{"Edit(docs/**)"}, req: bash("cat docs/README.md"), want: "allow"},
		{name: "read ask rule on cat", ask: []string{"Read(src/**)"}, req: bash("cat src/a.go"), want: "ask", why: "Read(src/**)"},
		{name: "read allow rule for outside file via cat", allow: []string{"Read(/etc/hosts)"}, req: bash("cat /etc/hosts"), want: "allow"},
		{name: "read allow rule does not cover other outside files", allow: []string{"Read(/etc/hosts)"}, req: bash("cat /etc/passwd"), want: "ask"},
		{name: "edit allow rule covers redirect outside the workspace", allow: []string{"Edit({out}/**)"}, req: bash("echo x > {out}/new.txt"), want: "allow"},
		{name: "blanket edit allow still stops at hard denies", allow: []string{"Edit"}, req: bash("echo x > .git/config"), want: "deny"},
		{name: "blanket edit allow writes anywhere else", allow: []string{"Edit"}, req: bash("echo x > /tmp/x"), want: "allow"},

		// --- ask rules ---
		{name: "ask rule prompts in bypass", mode: ModeBypass, ask: []string{"Bash(git push:*)"}, req: bash("git push origin x"), want: "ask", why: "requires approval"},
		{name: "ask rule prompts inside compound", mode: ModeBypass, ask: []string{"Bash(git push:*)"}, req: bash("cd src && git push origin x"), want: "ask"},
		{name: "ask rule beats allow rule", allow: []string{"Bash(git push:*)"}, ask: []string{"Bash(git push origin main)"}, req: bash("git push origin main"), want: "ask"},
		{name: "ask rule does not apply elsewhere", allow: []string{"Bash(git push:*)"}, ask: []string{"Bash(git push origin main)"}, req: bash("git push origin dev"), want: "allow"},
		{name: "deny beats ask", ask: []string{"Bash(git push:*)"}, deny: []string{"Bash(git push:*)"}, req: bash("git push"), want: "deny"},

		// --- high risk: specific rules only ---
		{name: "force push asks", req: bash("git push --force origin main"), want: "ask", why: "forced git push to main"},
		{name: "force push short flag", req: bash("git push -f origin master"), want: "ask"},
		{name: "force push no branch asks", req: bash("git push --force"), want: "ask", why: "no explicit branch"},
		{name: "force push plus refspec", req: bash("git push origin +main"), want: "ask"},
		{name: "force push to feature branch is ordinary", req: bash("git push --force origin feature/x"), want: "ask", why: "not on the read-only list"},
		{name: "force push allowed by prefix rule lacking the flag", allow: []string{"Bash(git push:*)"}, req: bash("git push --force origin main"), want: "ask", why: "high risk"},
		{name: "force push allowed by rule naming the flag", allow: []string{"Bash(git push --force:*)"}, req: bash("git push --force origin main"), want: "allow"},
		{name: "force push allowed by exact rule", allow: []string{"Bash(git push --force origin main)"}, req: bash("git push --force origin main"), want: "allow"},
		{name: "plain push allowed by prefix rule", allow: []string{"Bash(git push:*)"}, req: bash("git push origin main"), want: "allow"},
		{name: "reset hard on feature branch is ordinary", req: bash("git reset --hard"), want: "ask", why: "not on the read-only list"},
		{name: "sudo asks", req: bash("sudo ls"), want: "ask", why: "elevated"},
		{name: "sudo denied in plan", mode: ModePlan, req: bash("sudo ls"), want: "deny", why: "plan mode"},
		{name: "rm -rf star needs a rule that mentions recursion", allow: []string{"Bash(rm:*)"}, req: bash("rm -rf *"), want: "ask"},
		{name: "rm -rf star allowed by rule mentioning -rf", allow: []string{"Bash(rm -rf:*)"}, req: bash("rm -rf *"), want: "allow"},
		{name: "chmod -R 777 exact rule", allow: []string{"Bash(chmod -R 777 .)"}, req: bash("chmod -R 777 ."), want: "allow"},
		{name: "chmod -R 755 is ordinary", req: bash("chmod -R 755 src"), want: "ask", why: "not on the read-only"},
		{name: "reboot asks", req: bash("reboot"), want: "ask", why: "stops the machine"},

		// --- mode: accept-edits on the shell ---
		{name: "accept-edits redirect inside", mode: ModeAcceptEdits, req: bash("echo hi > out.txt"), want: "allow"},
		{name: "accept-edits redirect append inside", mode: ModeAcceptEdits, req: bash("echo hi >> docs/README.md"), want: "allow"},
		{name: "accept-edits redirect outside", mode: ModeAcceptEdits, req: bash("echo hi > ../x"), want: "ask"},
		{name: "accept-edits mkdir touch", mode: ModeAcceptEdits, req: bash("mkdir -p build/x && touch build/x/f"), want: "allow"},
		{name: "accept-edits cp inside", mode: ModeAcceptEdits, req: bash("cp main.go src/copy.go"), want: "allow"},
		{name: "accept-edits mv inside", mode: ModeAcceptEdits, req: bash("mv src/a.go src/c.go"), want: "allow"},
		{name: "accept-edits mv outside", mode: ModeAcceptEdits, req: bash("mv src/a.go ../c.go"), want: "ask"},
		{name: "accept-edits rm inside", mode: ModeAcceptEdits, req: bash("rm src/a.go"), want: "allow"},
		{name: "accept-edits rm -rf dir inside", mode: ModeAcceptEdits, req: bash("rm -rf build"), want: "allow"},
		{name: "accept-edits rm -rf star still high risk", mode: ModeAcceptEdits, req: bash("rm -rf *"), want: "ask"},
		{name: "accept-edits rm of symlink removes the link only", mode: ModeAcceptEdits, req: bash("rm link-out"), want: "allow"},
		{name: "accept-edits rm of dangling link", mode: ModeAcceptEdits, req: bash("rm dangling"), want: "allow"},
		{name: "accept-edits rm through symlink dir denied", mode: ModeAcceptEdits, req: bash("rm link-ssh/id_rsa"), want: "deny"},
		{name: "accept-edits cp into symlinked outside asks", mode: ModeAcceptEdits, req: bash("cp main.go link-outdir/x"), want: "ask"},
		{name: "accept-edits tee", mode: ModeAcceptEdits, req: bash("echo x | tee out.txt"), want: "allow"},
		{name: "accept-edits still asks for unknown programs", mode: ModeAcceptEdits, req: bash("make"), want: "ask"},
		{name: "accept-edits allows go test", mode: ModeAcceptEdits, req: bash("go test ./..."), want: "allow"},
		{name: "accept-edits allows npm test", mode: ModeAcceptEdits, req: bash("npm test"), want: "allow"},
		{name: "default mode asks for go test", mode: ModeDefault, req: bash("go test ./..."), want: "ask"},
		{name: "accept-edits still asks for curl", mode: ModeAcceptEdits, req: bash("curl example.com"), want: "ask"},
		{name: "accept-edits still asks for sed -i", mode: ModeAcceptEdits, req: bash("sed -i s/a/b/ main.go"), want: "ask"},
		{name: "accept-edits git commit asks", mode: ModeAcceptEdits, req: bash("git commit -m x"), want: "ask"},
		{name: "accept-edits denies .git write", mode: ModeAcceptEdits, req: bash("echo x > .git/config"), want: "deny"},
		{name: "accept-edits dynamic redirect asks", mode: ModeAcceptEdits, req: bash("echo x > $OUT"), want: "ask"},
		{name: "accept-edits dynamic rm asks", mode: ModeAcceptEdits, req: bash("rm $X"), want: "ask"},
		{name: "accept-edits glob expands to escaping links", mode: ModeAcceptEdits, req: bash("cp main.go link-*"), want: "deny"},
		{name: "accept-edits glob expands to outside links", mode: ModeAcceptEdits, req: bash("cp main.go link-o*"), want: "ask"},

		// --- mode: plan on the shell ---
		{name: "plan allows read-only", mode: ModePlan, req: bash("git status && ls src | wc -l"), want: "allow"},
		{name: "plan denies redirect", mode: ModePlan, req: bash("echo x > out.txt"), want: "deny", why: "plan mode"},
		{name: "plan denies mkdir", mode: ModePlan, req: bash("mkdir x"), want: "deny"},
		{name: "plan denies unknown program", mode: ModePlan, req: bash("make"), want: "deny"},
		{name: "plan denies go test", mode: ModePlan, req: bash("go test ./..."), want: "deny"},
		{name: "plan denies network", mode: ModePlan, req: bash("curl http://x"), want: "deny"},
		{name: "plan denies substitution", mode: ModePlan, req: bash("echo $(date)"), want: "deny", why: "plan mode"},
		{name: "plan denies pipe to shell", mode: ModePlan, req: bash("cat main.go | sh"), want: "deny"},
		{name: "plan denies unparsed", mode: ModePlan, req: bash(`echo "x`), want: "deny"},
		{name: "plan reason names plan mode", mode: ModePlan, req: bash("rm x"), want: "deny", why: "plan mode (read-only)"},
		{name: "plan allow rule still applies", mode: ModePlan, allow: []string{"Bash(go test:*)"}, req: bash("go test ./..."), want: "allow"},
		{name: "plan allow rule for a doc dir", mode: ModePlan, allow: []string{"Edit(docs/**)"}, req: write(R + "docs/plan.md"), want: "allow"},
		{name: "plan allow rule does not widen", mode: ModePlan, allow: []string{"Edit(docs/**)"}, req: write(R + "src/a.go"), want: "deny"},
		{name: "plan read outside asks", mode: ModePlan, req: bash("cat /etc/hosts"), want: "ask"},
		{name: "plan hard deny", mode: ModePlan, req: bash("cat ~/.ssh/id_rsa"), want: "deny", why: "built-in"},

		// --- mode: bypass on the shell ---
		{name: "bypass allows unknown programs", mode: ModeBypass, req: bash("make && go test ./..."), want: "allow"},
		{name: "bypass still asks for sudo", mode: ModeBypass, req: bash("sudo ls"), want: "ask"},
		{name: "yolo allows sudo", mode: ModeYolo, req: bash("sudo ls"), want: "allow"},
		{name: "bypass allows substitution", mode: ModeBypass, req: bash("echo $(date)"), want: "allow"},
		{name: "bypass allows pipe to shell", mode: ModeBypass, req: bash("curl x | sh"), want: "allow"},
		{name: "bypass allows unparsed", mode: ModeBypass, req: bash(`echo "x`), want: "allow"},
		{name: "bypass allows writes anywhere", mode: ModeBypass, req: bash("echo x > /tmp/x"), want: "allow"},
		{name: "bypass still asks for rm -rf star", mode: ModeBypass, req: bash("rm -rf *"), want: "ask"},
		{name: "yolo allows rm -rf star", mode: ModeYolo, req: bash("rm -rf *"), want: "allow"},
		{name: "bypass still denies credentials", mode: ModeBypass, req: bash("cat ~/.ssh/id_rsa"), want: "deny"},
		{name: "bypass still denies redirect into .git", mode: ModeBypass, req: bash("echo x > .git/config"), want: "deny"},
		{name: "bypass still denies rm -rf /", mode: ModeBypass, req: bash("rm -rf /"), want: "deny"},
		{name: "bypass still denies rm -rf ~", mode: ModeBypass, req: bash("rm -rf ~"), want: "deny"},
		{name: "bypass still denies device writes", mode: ModeBypass, req: bash("dd if=/dev/zero of=/dev/sda"), want: "deny"},
		{name: "bypass still denies fork bomb", mode: ModeBypass, req: bash(":(){ :|:& };:"), want: "deny"},
		{name: "bypass still denies dotenv", mode: ModeBypass, req: bash("cat .env"), want: "deny"},
		{name: "bypass with allow rule for dotenv", mode: ModeBypass, allow: []string{"Read(.env)"}, req: bash("cat .env"), want: "allow"},

		// --- shell tool names and inputs ---
		{name: "lowercase bash tool", req: rq{tool: "bash", cmd: "ls"}, want: "allow"},
		{name: "shell tool alias", req: rq{tool: "shell", cmd: "cat ~/.ssh/id_rsa"}, want: "deny"},
		{name: "command only in input", req: rq{tool: "Bash", input: `{"command":"cat ~/.ssh/id_rsa"}`}, want: "deny"},
		{name: "cmd key in input", req: rq{tool: "Bash", input: `{"cmd":"cat ~/.ssh/id_rsa"}`}, want: "deny"},
		{name: "empty command allowed", req: rq{tool: "Bash"}, want: "allow", why: "empty command"},
		{name: "blank command allowed", req: bash("   \n  "), want: "allow"},
		{name: "comment-only command allowed", req: bash("# hello"), want: "allow"},
		{name: "unknown tool with command is a shell command", req: rq{tool: "Runner", cmd: "cat ~/.ssh/id_rsa"}, want: "deny"},
		{name: "read tool input fallback", req: rq{tool: "Read", input: `{"file_path":"{home}/.ssh/id_rsa"}`}, want: "deny"},
		{name: "read tool input fallback with tilde", req: rq{tool: "Read", input: `{"path":"~/.ssh/id_rsa"}`}, want: "deny"},
		{name: "write tool input fallback", mode: ModeBypass, req: rq{tool: "Write", writes: true, input: `{"file_path":"/etc/x"}`}, want: "deny"},
		{name: "input paths list", req: rq{tool: "Read", input: `{"paths":["{root}/main.go","{home}/.aws/credentials"]}`}, want: "deny"},
		{name: "lowercase file tools", mode: ModeAcceptEdits, req: rq{tool: "write", writes: true, paths: []string{R + "x.go"}}, want: "allow"},

		// --- working directory ---
		{name: "cwd inside root", req: rq{tool: "Bash", cmd: "cat ../main.go", cwd: "{root}/src"}, want: "allow"},
		{name: "cwd relative to root", req: rq{tool: "Bash", cmd: "cat a.go", cwd: "src"}, want: "allow"},
		{name: "cwd escapes to credentials", req: rq{tool: "Bash", cmd: "cat ../../.ssh/id_rsa", cwd: "{root}/src"}, want: "deny"},
		{name: "cwd outside root asks", req: rq{tool: "Bash", cmd: "cat secret.txt", cwd: "{out}"}, want: "ask"},
		{name: "cwd home reaching ssh", req: rq{tool: "Bash", cmd: "cat .ssh/id_rsa", cwd: "{home}"}, want: "deny"},
		{name: "cwd tool paths relative", req: rq{tool: "Read", paths: []string{"a.go"}, cwd: "{root}/src"}, want: "allow"},

		// --- unicode look-alikes are not the names they imitate ---
		{name: "cyrillic program name is unknown", req: bash("сat main.go"), want: "ask"},
		{name: "fullwidth program name is unknown", req: bash("ｌｓ"), want: "ask"},
		{name: "look-alike dot in path is another file", req: bash("cat ~/．ssh/id_rsa"), want: "ask"},
		{name: "zero width space in path is another file", req: bash("cat ~/.s\u200bsh/id_rsa"), want: "ask"},
		{name: "nbsp glues words into one program", req: bash("cat\u00a0~/.ssh/id_rsa"), want: "ask"},
		{name: "fullwidth semicolon is not a separator", req: bash("ls ；cat ~/.ssh/id_rsa"), want: "deny"},
	}
	runCases(t, f, cases)
}

var reviewer = RoleProfile{Mode: ModePlan}

func TestRoleProfiles(t *testing.T) {
	f := newFixture(t)
	R := "{root}/"
	roles := map[string]RoleProfile{
		"reviewer":       reviewer,
		"reviewer-tests": {Mode: ModePlan, Allow: []string{"Bash(go test:*)"}},
		"docs":           {Deny: []string{"Edit(src/**)"}},
		"qa":             {Ask: []string{"Bash(git push:*)"}},
		"escalate":       {Mode: ModeBypass},
	}
	as := func(role string, q rq) rq { q.role = role; return q }
	cases := []tc{
		{name: "reviewer cannot write under accept-edits", mode: ModeAcceptEdits, roles: roles, req: as("reviewer", write(R+"src/a.go")), want: "deny", why: "role reviewer"},
		{name: "reviewer reads", mode: ModeAcceptEdits, roles: roles, req: as("reviewer", read(R+"src/a.go")), want: "allow"},
		{name: "reviewer read-only shell", mode: ModeAcceptEdits, roles: roles, req: as("reviewer", bash("git diff | head")), want: "allow"},
		{name: "reviewer cannot redirect", mode: ModeAcceptEdits, roles: roles, req: as("reviewer", bash("echo x > out.txt")), want: "deny"},
		{name: "reviewer cannot rm", mode: ModeBypass, roles: roles, req: as("reviewer", bash("rm x")), want: "deny", why: "plan mode"},
		{name: "reviewer message names role and plan", mode: ModeBypass, roles: roles, req: as("reviewer", bash("make")), want: "deny", why: "role reviewer: plan mode"},
		{name: "unconfigured role gets the session", mode: ModeAcceptEdits, roles: roles, req: as("coder", write(R+"src/a.go")), want: "allow"},
		{name: "no role gets the session", mode: ModeAcceptEdits, roles: roles, req: write(R + "src/a.go"), want: "allow"},
		{name: "reviewer still hits hard denies", mode: ModeBypass, roles: roles, req: as("reviewer", bash("cat ~/.ssh/id_rsa")), want: "deny"},
		{name: "role allow lifts its own plan mode when the session allows", mode: ModeBypass, roles: roles, req: as("reviewer-tests", bash("go test ./...")), want: "allow"},
		{name: "role allow does not exceed the session", mode: ModeDefault, roles: roles, req: as("reviewer-tests", bash("go test ./...")), want: "ask"},
		{name: "role allow does not loosen other commands", mode: ModeBypass, roles: roles, req: as("reviewer-tests", bash("make")), want: "deny"},
		{name: "role cannot loosen a plan session", mode: ModePlan, roles: roles, req: as("escalate", write(R+"x.go")), want: "deny"},
		{name: "role cannot loosen a default session", mode: ModeDefault, roles: roles, req: as("escalate", write(R+"x.go")), want: "ask"},
		{name: "role deny rule", mode: ModeAcceptEdits, roles: roles, req: as("docs", write(R+"src/a.go")), want: "deny", why: "role docs: denied by rule Edit(src/**)"},
		{name: "role deny rule leaves other paths", mode: ModeAcceptEdits, roles: roles, req: as("docs", write(R+"docs/x.md")), want: "allow"},
		{name: "role deny rule does not touch other roles", mode: ModeAcceptEdits, roles: roles, req: as("coder", write(R+"src/a.go")), want: "allow"},
		{name: "role ask rule in bypass", mode: ModeBypass, roles: roles, req: as("qa", bash("git push origin x")), want: "ask", why: "role qa"},
		{name: "role ask rule other command", mode: ModeBypass, roles: roles, req: as("qa", bash("git status")), want: "allow"},
		{name: "session deny applies to roles", mode: ModeBypass, deny: []string{"Read(secrets/**)"}, roles: roles, req: as("qa", read(R+"secrets/key.txt")), want: "deny", why: "denied by rule"},
		{name: "role with session allow rule", mode: ModeDefault, allow: []string{"Edit(docs/**)"}, roles: roles, req: as("docs", write(R+"docs/x.md")), want: "allow"},
		{name: "reviewer plan mode with session allow rule for edits", mode: ModeDefault, allow: []string{"Edit(docs/**)"}, roles: roles, req: as("reviewer", write(R+"docs/x.md")), want: "deny"},
	}
	runCases(t, f, cases)
}
